// lib/policyFundsSeed.js
// 정책자금 마스터 DB의 초기 데이터.
// 출처: app/api/chat/route.js(AI 상담 시스템 프롬프트), lib/policyFundAnalysis.js, lib/policyFundEstimate.js,
//       app/components/PolicyFundAnalyzer.jsx — 2026-09-02 기준으로 거기 있던 지식을 하나도 빼지 않고 구조화한 것.
// 이 파일은 "DB가 비어있을 때 최초 1회" 채우는 용도. 이후 수정은 /admin/policy-funds 관리자 화면에서 하고,
// 이 파일은 백업/참고용으로만 남겨둠 (관리자 화면에서 고친 내용이 이 파일에 자동 반영되지는 않음).
//
// 금액 단위: 전부 만원.
//
// SEED_VERSION: 이 파일을 고칠 때마다 올린다. lib/policyFundsStore.js가 배포 후 첫 호출 때 버전이 바뀐 걸 보고
//   DB의 시드 항목을 갱신함. 단, 관리자 화면에서 직접 고친 항목(updated_by가 'seed'가 아닌 것)은 덮어쓰지 않음.
//   → 대표가 말로 알려준 수정사항은 Claude가 이 파일에 반영 + 버전 올림 → 배포되면 자동 적용. 이게 기본 흐름.
//
// conditions: [{ text, kind }] — kind는 'required'(전부 충족) / 'any'(any끼리 묶어서 그중 1개만) / 'bonus'(가점 — 없어도 신청 가능)
// reapply_rule: { type: 'none' | 'months' | 'announcement', months, months_by_region: {수도권, 지방}, note }
//   - months: 마지막 수령일 기준 재신청 가능까지 개월 수
//   - announcement: 제한기간은 없지만 공고가 떠야 신청 가능 (소진공) → 부결 고객은 공고 알림과 연결
// criteria: 자격 자동판정 엔진이 읽는 수치/플래그 (선택). 없는 키는 판정에서 무시.

export const SEED_VERSION = '2026-09-02.4'

// 예전 시드 버전에서 쓰던 키 중 이제 안 쓰는 것. 버전 갱신 때 DB에서 지움(시드가 만든 행만 — 관리자가 직접 고친 행은 남김).
export const SEED_DEPRECATED_KEYS = [
  'jungjingong', // v1 placeholder
  'jungjingong_youth_startup', 'jungjingong_innovation_startup', 'jungjingong_growth_base', 'jungjingong_rebound', // v2 웹조사 초안 → kosme_* 로 교체
]

export const SEED_FUNDS = [
  // ───────────────────────── 소진공 직접대출 ─────────────────────────
  {
    key: 'sojinkong_hyuksin_general',
    name: '혁신성장촉진자금 일반형',
    institution: '소상공인시장진흥공단',
    fund_type: '직접대출',
    limit_operating: 10000,
    limit_facility: 50000,
    cap_group: '소진공_기본_1억',
    rate_note: '정책자금 기준금리 + 0.4%p',
    period_note: '운전 5년 (거치 2년) / 시설 8년 (거치 3년)',
    eligibility_summary: '아래 스마트기기 중 1개 이상을 도입·운영 중인 소상공인. 소진공 직접대출 총한도 1억(잔액 합산) 안에서 신청.',
    conditions: [
      { kind: 'required', text: '스마트기기 1개 이상 도입·운영 중 (아래 목록 참고)' },
      { kind: 'required', text: '소진공 직접대출 잔여한도 있음 (총한도 1억 - 현재 잔액)' },
    ],
    smart_devices: [
      '3D 풋스캐너 / 3D 프린터',
      'AI CCTV / AI 두피분석 / AI 안면인식',
      'AI·IOT 온도관리시스템',
      '주문·예약·결제 키오스크',
      'QR/NFC 오더 / 테이블 오더',
      'AI·무게형·모듈형 무인판매기',
      '서빙로봇 / 헬퍼로봇 / 조리로봇',
      '디지털광고보드 / 디지털메뉴보드',
      '고객관리·예약·매출분석·재고관리 S/W',
      '온라인예약관리 / 매장멤버십관리시스템',
      '축산 육가공공정시스템',
    ],
    criteria: { requires_smart_device: true },
    reapply_rule: { type: 'announcement', note: '재신청 제한기간 없음. 공고가 떠야 신청 가능 — 부결 시 다음 공고 알림과 연결' },
    required_docs: ['사업자등록증명', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서', '스마트기기 도입 증빙(구매계약서·영수증·사진 등)'],
    exclusive_group: '소진공_직접대출', // 소진공 직접대출은 결과 나올 때까지 한 번에 1개만 접수 가능,
    notes: '2026년 4월부터 스마트기기 목록에서 배달앱·자동화기기 삭제됨.',
    sort_order: 10,
  },
  {
    key: 'sojinkong_hyuksin_innovative',
    name: '혁신성장촉진자금 혁신형',
    institution: '소상공인시장진흥공단',
    fund_type: '직접대출',
    limit_operating: 20000,
    limit_facility: 100000,
    cap_group: '소진공_확장_2억',
    rate_note: '정책자금 기준금리 + 0.4%p',
    period_note: '운전 5년 (거치 2년) / 시설 8년 (거치 3년)',
    eligibility_summary: '일반형 요건(스마트기기)을 충족하면서 아래 성장 요건 중 1개 이상 해당. 총한도 2억 별도 적용.',
    conditions: [
      { kind: 'required', text: '스마트기기 1개 이상 도입·운영 중 (일반형 요건)' },
      { kind: 'any', text: '최근 1년 수출 실적 1천달러 이상 (수출실적증명원 발급 가능)' },
      { kind: 'any', text: '23년→24년, 24년→25년 매출 연속 10% 이상 증가 (단 23년 매출 5천만원 이상)' },
      { kind: 'any', text: '소진공 직접대출 원금분할상환 중 또는 최근 3년 내 완제 (거치기간 중이면 해당 안 됨)' },
      { kind: 'any', text: '스마트공장 도입 / 강한소상공인·로컬크리에이터 선정' },
    ],
    criteria: { requires_smart_device: true, credit_min_recommended: 700 },
    reapply_rule: { type: 'announcement', note: '재신청 제한기간 없음. 공고가 떠야 신청 가능' },
    required_docs: ['사업자등록증명', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서', '재무제표(복식부기 대상자)', '수출실적증명원 또는 매출 증가 증빙 등 해당 요건 증빙'],
    exclusive_group: '소진공_직접대출', // 소진공 직접대출은 결과 나올 때까지 한 번에 1개만 접수 가능,
    notes: '신용점수 공식 제한 없으나 실전 기준 700점 이상 권장.',
    sort_order: 20,
  },
  {
    key: 'sojinkong_jaedo_general',
    name: '재도전특별자금 일반형',
    institution: '소상공인시장진흥공단',
    fund_type: '직접대출',
    limit_operating: 7000,
    limit_facility: null,
    cap_group: '소진공_기본_1억',
    rate_note: '정책자금 기준금리 + 0.4%p',
    period_note: '운전 5년 (거치 2년) / 시설 8년 (거치 3년)',
    eligibility_summary: '현재 사업자 1개 + 업력 7년 미만이면서, 폐업이력 등 재도전 사유가 있는 소상공인.',
    conditions: [
      { kind: 'required', text: '현재 대표자 명의 사업자 1개 (2개 이상이면 불가)' },
      { kind: 'required', text: '업력 7년 미만' },
      { kind: 'any', text: '과거 폐업 이력 있음' },
      { kind: 'any', text: '업종 전환 이력 있음' },
      { kind: 'any', text: '3개월 이상 휴업 이력 있음' },
      { kind: 'any', text: '매출 감소로 사업장 이전 이력 있음' },
    ],
    criteria: { max_biz_age_exclusive: 7, current_biz_count: 1, requires_closure_or_restart_history: true },
    reapply_rule: { type: 'announcement', note: '재신청 제한기간 없음. 공고가 떠야 신청 가능' },
    required_docs: ['사업자등록증명', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서', '폐업사실증명(폐업이력 증빙) 또는 해당 사유 증빙'],
    exclusive_group: '소진공_직접대출', // 소진공 직접대출은 결과 나올 때까지 한 번에 1개만 접수 가능,
    notes: '폐업사실증명 API는 CODEF에서 2026년 9월 중 제공 예정.',
    sort_order: 30,
  },
  {
    key: 'sojinkong_jaedo_leap',
    name: '재도전특별자금 도약형',
    institution: '소상공인시장진흥공단',
    fund_type: '직접대출',
    limit_operating: 20000,
    limit_facility: null,
    cap_group: '소진공_확장_2억',
    rate_note: '정책자금 기준금리 + 0.4%p',
    period_note: '운전 5년 (거치 2년) / 시설 8년 (거치 3년)',
    eligibility_summary: '재창업 업력 2~7년 + 소진공 성실상환 + 성장 요건 중 1개.',
    conditions: [
      { kind: 'required', text: '재창업 업력 2년 이상 7년 미만' },
      { kind: 'required', text: '소진공 직접대출 성실상환 (원금분할상환 중)' },
      { kind: 'any', text: '직원 2명 이상' },
      { kind: 'any', text: '24년→25년 매출 5% 이상 증가' },
      { kind: 'any', text: '최근 6개월 vs 이전 6개월 매출 5% 이상 증가' },
    ],
    criteria: { min_biz_age: 2, max_biz_age_exclusive: 7, requires_sojinkong_good_repayment: true },
    reapply_rule: { type: 'announcement', note: '재신청 제한기간 없음. 공고가 떠야 신청 가능' },
    required_docs: ['사업자등록증명', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서', '재무제표(복식부기 대상자)', '4대보험 가입자명부(직원 요건 시)'],
    exclusive_group: '소진공_직접대출', // 소진공 직접대출은 결과 나올 때까지 한 번에 1개만 접수 가능,
    notes: null,
    sort_order: 40,
  },
  {
    key: 'sojinkong_credit_vulnerable',
    name: '신용취약소상공인자금',
    institution: '소상공인시장진흥공단',
    fund_type: '직접대출',
    limit_operating: 3000,
    limit_facility: null,
    cap_group: '신용취약_3천',
    rate_note: '정책자금 기준금리 + 0.4%p',
    period_note: '5년 (거치 2년)',
    eligibility_summary: 'NICE 신용점수 595~839점 구간 + 국세·지방세 체납 없음 + 연체 없음. 자금 자체 한도 3천만원(잔액 합산).',
    conditions: [
      { kind: 'required', text: 'NICE 신용점수 595점 이상 839점 이하' },
      { kind: 'required', text: '국세·지방세 체납 없음' },
      { kind: 'required', text: '금융권 연체 없음' },
      { kind: 'required', text: '이 자금 잔여한도 있음 (3천만원 - 기존 신용취약자금 잔액)' },
    ],
    criteria: { credit_min: 595, credit_max: 839, no_tax_delinquency: true, no_overdue: true },
    reapply_rule: { type: 'announcement', note: '재신청 제한기간 없음. 공고가 떠야 신청 가능' },
    required_docs: ['사업자등록증명', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서'],
    exclusive_group: '소진공_직접대출', // 소진공 직접대출은 결과 나올 때까지 한 번에 1개만 접수 가능,
    notes: '신용점수 839점 초과면 대상 범위 초과, 595점 미달이면 최저 기준 미달.',
    sort_order: 50,
  },
  {
    key: 'sojinkong_temporary_hardship',
    name: '일시적경영애로자금',
    institution: '소상공인시장진흥공단',
    fund_type: '직접대출',
    limit_operating: 7000,
    limit_facility: null,
    cap_group: '소진공_기본_1억',
    rate_note: '정책자금 기준금리 + 0.4%p',
    period_note: '운전 5년 (거치 2년)',
    eligibility_summary: '연매출 1억 400만원 미만 + 업력 7년 미만 + 매출 15% 이상 감소(연간·반기·분기 등 공고 비교기준 중 하나).',
    conditions: [
      { kind: 'required', text: '연매출 1억 400만원 미만' },
      { kind: 'required', text: '업력 7년 미만' },
      { kind: 'required', text: '매출 15% 이상 감소 — 전년 대비 연매출, 직전 반기 대비, 직전 분기 대비 등 공고에서 정한 비교기간 중 하나 충족' },
    ],
    criteria: { sales_max_exclusive: 10400, max_biz_age_exclusive: 7, requires_sales_decline_pct: 15, sales_decline_compare_periods: ['연간', '반기', '분기'] },
    reapply_rule: { type: 'announcement', note: '재신청 제한기간 없음. 공고가 떠야 신청 가능' },
    required_docs: ['사업자등록증명', '부가세과세표준증명(매출 감소 증빙)', '납세증명서(국세)', '지방세 납세증명서'],
    exclusive_group: '소진공_직접대출', // 소진공 직접대출 공통 규칙(한 번에 1개)
    notes: '매출 감소 비교기간은 공고에 따라 전년 대비 연매출 / 반기 대비 / 분기 대비 등으로 열려 있음 — 해당 공고의 비교기준을 확인해서 유리한 것으로 증빙.',
    sort_order: 60,
  },

  // ───────────────────────── 보증기관 (간접대출) ─────────────────────────
  {
    key: 'jaedan',
    name: '신용보증재단',
    institution: '지역신용보증재단',
    fund_type: '보증',
    limit_operating: 10000,
    limit_facility: null,
    cap_group: '재단_1억',
    rate_note: '은행 대출금리 적용',
    period_note: '은행별 상이',
    eligibility_summary: '원래 소매업·요식업 등 규모가 작은 사업자를 위한 신용보증(도매·큰 기업은 신용보증기금). 매출 규모와 무관하게 재단 한도 1억(잔액 합산)을 안 쓰고 있으면 검토 대상. "도소매업"으로 묶인 업종은 원칙적으로 재단·신보 둘 다 가능. 신보(기금) 이용 중이어도 재단이 추가로 해주는 사례 있음(매출 17억 대표: 신보 3억 + 재단 1억). 기보와는 공동 보유 불가.',
    conditions: [
      { kind: 'required', text: '잔여 보증한도 있음 (1억 - 기존 재단 보증 잔액) — 매출 규모 무관하게 미사용이면 검토' },
      { kind: 'required', text: '기보 보증을 보유 중이 아님 — 재단과 기보는 공동 보유 불가(기보가 재단 대출을 갚아주고 추가대출하는 대환 형태만 가능)' },
      { kind: 'required', text: '신보(기금)와는 같은 신용보증이라 기금 이용 중이어도 재단이 추가로 해주는 경우가 있음 — 재단 한도 미사용이면 검토' },
      { kind: 'required', text: '기존 재단 보증이 있으면 재신청 대기기간 경과' },
    ],
    criteria: {},
    reapply_rule: {
      type: 'months',
      months_by_region: { 수도권: 12, 지방: 6 },
      note: '마지막 보증 수령일 기준. 서울·경기(수도권) 1년 이상, 그 외 지역 6개월 이상. 재단 보증 있으면 반드시 "언제 받으셨나요? 서울/경기인가요?" 먼저 확인.',
    },
    required_docs: ['사업자등록증명', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서', '재무제표(복식부기 대상자)'],
    exclusive_group: '보증기관',
    notes: '업종 원칙: 도매→신용보증기금, 소매·요식→신용보증재단(같은 신용보증인데 도매가 규모가 커서). 도소매업으로 묶인 사업자는 둘 다 가능. 소진공 직접대출과 동시진행 순서: ① 소진공 직접대출 접수 → ② 재단 추가 보증 접수 → ③ 보증서 수령 후 대기 → ④ 소진공 심사 완료 후 약정·입금 → ⑤ 보증서 들고 은행 방문하여 보증대출 실행. 신보 대상 규모면 신보가 재단 대출을 대환하며 보증서 재발급하는 경우 있음.',
    sort_order: 100,
  },
  {
    key: 'shinbo',
    name: '신용보증기금 (신보)',
    institution: '신용보증기금',
    fund_type: '보증',
    limit_operating: null,
    limit_facility: null,
    cap_group: null,
    rate_note: '은행 대출금리 적용',
    period_note: '은행별 상이',
    eligibility_summary: '신용·재무(매출·재무제표)를 평가해서 보증하는 기관. 업종은 거의 장벽이 아님 — 제조·도소매·IT·건설·서비스 등 자격·매출·재무제표만 되면 검토 대상. 유일한 업종 예외는 요식업(프랜차이즈·가맹이면 가능). 규모 참고선: 도소매·서비스 매출 5억↑(한도 통상 매출÷6 수준), 제조 3억↑(통상 ÷4 수준) — 참고선일 뿐 확정 기준이 아니고 실제 한도는 심사에 따라 달라짐(도소매 매출 16억 대표가 3억 받은 사례). 기보와 절대 동시 이용 불가.',
    conditions: [
      { kind: 'any', text: '도소매·서비스업: 연매출 5억 이상 → 한도 통상 매출 ÷ 6 수준 (심사에 따라 상이)' },
      { kind: 'any', text: '제조업: 연매출 3억 이상 → 한도 통상 매출 ÷ 4 수준 (심사에 따라 상이)' },
      { kind: 'any', text: '프랜차이즈·가맹 요식업: 연매출 5억 이상 → 한도 통상 매출 ÷ 6 수준 (가맹 여부 등 별도 심사)' },
      { kind: 'required', text: '비프랜차이즈 요식업 아님 — 이것만 유일한 업종 예외. 제조·도소매·IT·건설·서비스 등은 업종 무관' },
      { kind: 'required', text: '기보 보증을 보유 중이 아님 — 신보와 기보는 무조건 동시 이용 불가. 기보 이용 중이면 다 갚고 오거나, 신보가 기보 대출을 갚아주고 추가대출하는 대환 형태만 가능(하나 쓰고 있으면 상대적으로 매우 어려움)' },
      { kind: 'required', text: '재단과는 같은 신용보증 계열 — 재단 이용 중이어도 규모가 되면 신보로 올라가는(재단 대출 대환) 경우 있음' },
      { kind: 'required', text: '기존 신보 보증이 있으면 1년 경과' },
      { kind: 'bonus', text: '기업부설연구소 보유' },
      { kind: 'bonus', text: '벤처기업 인증' },
    ],
    criteria: {
      limit_formula: { 도소매서비스: { sales_min: 50000, divisor: 6 }, 제조: { sales_min: 30000, divisor: 4 }, 프랜차이즈요식: { sales_min: 50000, divisor: 6 } },
      limit_formula_is_typical: true,
      excluded_industries: ['일반 요식업'],
    },
    reapply_rule: { type: 'months', months: 12, note: '마지막 보증 수령일 기준 1년' },
    required_docs: ['사업자등록증명', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서', '재무제표'],
    exclusive_group: '보증기관',
    notes: '평가 축: 신용과 재무(매출·재무제표). 한도 공식(÷6, ÷4)은 통상 수준일 뿐 확정치가 아님 — 안내할 때 "통상적으로"를 붙일 것. 기보와 공동 보유 불가(대환만). 재단 대출 보유 시 신보가 재단 대출을 대환하며 보증서 재발급하는 경우 있음.',
    sort_order: 110,
  },
  {
    key: 'gibo',
    name: '기술보증기금 (기보)',
    institution: '기술보증기금',
    fund_type: '보증',
    limit_operating: null,
    limit_facility: null,
    cap_group: null,
    rate_note: '은행 대출금리 적용',
    period_note: '은행별 상이',
    eligibility_summary: '기술 쪽 비중이 가장 큼 — 특허·연구소·경력·기술력 같은 비재무 요소를 제일 많이 보고, 매출·재무제표도 보긴 하지만 그보다 비재무를 더 많이 봄. 핵심 요건: 기술특허 보유 또는 대표자 경력 10년 이상. 업종은 장벽 아님(비프랜차이즈 요식업만 예외). 한도는 기술력·매출 종합해 심사 시 결정. 신보·재단과 공동 보유 불가 — 대환 형태만 가능.',
    conditions: [
      { kind: 'any', text: '기술특허 보유' },
      { kind: 'any', text: '대표자 동업종 경력 10년 이상' },
      { kind: 'required', text: '비프랜차이즈 요식업 아님 — 유일한 업종 예외' },
      { kind: 'required', text: '신보 보증을 보유 중이 아님 — 신보와 기보는 무조건 동시 이용 불가. 신보 이용 중이면 다 갚고 오거나 기보가 갚아주고 추가대출(대환)만 가능, 매우 어려움' },
      { kind: 'required', text: '재단 보증을 보유 중이 아님 — 재단 쓰고 있으면 기보가 안 해줄 때가 많음. 단 규모·기술·특허·경력이 모두 좋으면 기보가 재단 대출을 갚아주고 추가대출하는 경우 있음' },
      { kind: 'required', text: '기존 기보 보증이 있으면 1년 경과' },
      { kind: 'bonus', text: '기업부설연구소 보유 — 있으면 가점, 없어도 신청 가능' },
      { kind: 'bonus', text: '벤처기업 인증 — 있으면 가점, 없어도 신청 가능' },
    ],
    criteria: { requires_patent_or_career_years: 10, excluded_industries: ['일반 요식업'] },
    reapply_rule: { type: 'months', months: 12, note: '마지막 보증 수령일 기준 1년' },
    required_docs: ['사업자등록증명', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서', '재무제표', '특허증 또는 경력 증빙'],
    exclusive_group: '보증기관',
    notes: '평가 비중: 비재무(특허·연구소·경력·기술) > 재무(매출·재무제표). 기업부설연구소·벤처인증은 가점 요소일 뿐 필수 아님 — 없다고 불가라고 안내하지 말 것. 한도는 특정 금액을 미리 계산해 보여주지 않음.',
    sort_order: 120,
  },

  // ───────────────────────── 중진공 (중소벤처기업진흥공단) ─────────────────────────
  // 근거: 2026년도 중소기업 정책자금 융자계획 변경공고(중기부 공고 제2026-464호) + 참고자료 + 중진공 기초 가이드.
  // 원본은 docs/knowledge/kosme-2026/ 에 보관(hwpx·pdf·텍스트 추출본).
  // 공통 제한(소상공인 원칙 제외, 융자제외 업종, 부채비율, 5년 3회 등)은 공통 규칙 'jungjingong_general' 참고.
  {
    key: 'kosme_startup_base',
    name: '중진공 창업기반지원자금 (일반)',
    institution: '중소벤처기업진흥공단',
    fund_type: '직접대출',
    limit_operating: 50000,
    limit_facility: 600000,
    cap_group: '중진공_60억',
    rate_note: '운전: 정책자금 기준금리(분기별 변동) − 0.3%p / 시설: 기준금리 − 0.6%p. 우대금리 최대 0.4%p 추가 가능',
    period_note: '시설 10년 이내(거치 담보 4년·신용 3년) / 운전 5년 이내(거치 2년)',
    eligibility_summary: '업력 7년 미만 창업자(예비창업자 포함) 또는 신산업 창업 분야 업력 10년 이내 중소기업. 연간 60억(운전 5억) 이내. 소상공인은 원칙 제외(혁신성장·초격차·신산업 분야 소상공인은 가능).',
    conditions: [
      { kind: 'required', text: '업력 7년 미만 (사업개시일~융자신청서 제출일; 법인전환 시 최초 창업 기업 사업개시일 기준). 신산업 창업 분야는 10년 이내' },
      { kind: 'required', text: '중소기업기본법상 중소기업이며 소상공인이 아님 (소상공인은 혁신성장·초격차·신산업 분야 영위 시에만 가능)' },
      { kind: 'required', text: '융자제외 업종 아님 · 세금체납 없음 · 신용정보원 연체·부도 등 등록 없음 · 업종별 제한 부채비율 이내(간편장부대상자는 부채비율 예외)' },
      { kind: 'bonus', text: '유망기업 인증(소부장 강소기업100·초격차·아기유니콘 등), 여성·장애인·사회적경제기업, 신보 매출채권보험 가입(운전자금) → 금리 우대' },
    ],
    criteria: { max_biz_age_exclusive: 7, excludes_small_business: true, small_business_exception_sectors: ['혁신성장분야', '초격차·신산업'] },
    reapply_rule: { type: 'announcement', note: '1/5부터 예산 소진 시까지 매월 첫째 주 온라인 접수. 기업평가 탈락·전액 포기 후 6개월간 재신청 제한. 최근 5년 내 3회 이상 지원 기업 제한' },
    required_docs: ['사업자등록증명', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서', '재무제표', '융자 신청서·사업계획서(중진공 양식)', '대부분 서류는 데이터 자동 연계 — 신청서와 일부 증빙만 제출'],
    exclusive_group: null,
    notes: '방식: 직접대출·대리대출·성장공유형·투자조건부. 마일스톤자금(소진공→중진공 졸업 소상공인)의 업력 7년 미만 트랙이 이 자금. 시설자금 한도 60억은 사업별 우대 시 100억.',
    sort_order: 200,
    active: true,
  },
  {
    key: 'kosme_youth_startup',
    name: '중진공 청년전용창업자금',
    institution: '중소벤처기업진흥공단',
    fund_type: '직접대출',
    limit_operating: 10000,
    limit_facility: 20000,
    cap_group: '중진공_60억',
    rate_note: '2.5% 고정금리 (우대금리 가감 대상 아님)',
    period_note: '시설 10년 이내(거치 담보 4년·신용 3년) / 운전 6년 이내(거치 3년)',
    eligibility_summary: '대표자 만 39세 이하 + 업력 3년 미만 중소기업(창업 예정자 포함). 기업당 1억 이내(제조업·중점지원분야는 2억 이내). 미래 성장성·기술력을 보는 자금 — 사업계획서 심의위원회(청년창업 평가위원회) 평가. 중점지원분야 소상공인은 신청 가능.',
    conditions: [
      { kind: 'required', text: '대표자 만 39세 이하' },
      { kind: 'required', text: '업력 3년 미만. 단 청년창업사관학교·글로벌창업사관학교 참여기업, 기보 청년창업기업보증 지원기업, 민간VC 투자유치 기업 중 해당 기관 추천 우수기업은 7년 미만까지' },
      { kind: 'required', text: '소상공인이면 중점지원분야(혁신성장·초격차·신산업·지역주력·뿌리·소부장 산업)를 영위해야 신청 가능' },
      { kind: 'required', text: '융자제외 업종 아님 · 세금체납 없음 · 신용정보원 등록 없음' },
      { kind: 'bonus', text: '제조업 또는 중점지원분야 영위 → 한도 2억' },
      { kind: 'bonus', text: '기술력·사업성 증빙(특허, 기업부설연구소, 벤처인증, 투자유치 등) — 심의위원회 평가에 유리' },
    ],
    criteria: { owner_age_max: 39, max_biz_age_exclusive: 3, limit_manufacturing_or_priority: 20000, excludes_small_business: true, small_business_exception_sectors: ['중점지원분야(참고1~4)'] },
    reapply_rule: { type: 'announcement', note: '1/5부터 예산 소진 시까지 매월 첫째 주 접수. 심의위원회 탈락 후 6개월 제한' },
    required_docs: ['사업자등록증명(또는 창업 예정 증빙)', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서', '재무제표(해당 시)', '사업계획서(심의위원회 평가용 — 가장 중요)', '대표자 신분증(나이 확인)', '기술·인증·투자 증빙(해당 시)'],
    exclusive_group: null,
    notes: '직접대출만. 대표 경험: 제조·IT 업종이 일반적, 요식업으로 받는 경우 본 적 없음(음식점은 융자제외 업종은 아니지만 소상공인 제외 규정과 심사에서 걸림).',
    sort_order: 210,
    active: true,
  },
  {
    key: 'kosme_tech_commercialization',
    name: '중진공 개발기술사업화자금',
    institution: '중소벤처기업진흥공단',
    fund_type: '직접대출',
    limit_operating: 50000,
    limit_facility: 300000,
    cap_group: '중진공_60억',
    rate_note: '운전: 정책자금 기준금리(변동) / 시설: 기준금리 − 0.3%p',
    period_note: '시설 10년 이내(거치 담보 4년·신용 3년) / 운전 5년 이내(거치 2년)',
    eligibility_summary: '업력 무관. 아래 유형의 기술을 사업화하려는 중소기업(양산 후 3년 경과 기술은 제외, 초격차 분야는 5년). 연간 30억(운전 5억); 혁신성장분야 + 유형①~⑤는 60억(운전 10억).',
    conditions: [
      { kind: 'any', text: '① 정부·지자체 출연 R&D 사업에 참여해 개발 성공(완료)한 기술' },
      { kind: 'any', text: '② 특허·실용신안·저작권 등록 기술' },
      { kind: 'any', text: '③ 정부 및 정부 공인기관이 인증한 기술' },
      { kind: 'any', text: '④ 공인 기업부설연구소·연구개발전담부서 보유 기업이 개발한 기술' },
      { kind: 'any', text: '⑤ 특허청 IP-R&D 전략지원 사업으로 개발 완료한 기술' },
      { kind: 'any', text: '⑥ 대학·연구기관·기업·기술거래기관에서 이전받은 기술' },
      { kind: 'any', text: '⑦ 중기부 인가기관과 기술자료 임치계약을 체결한 기술' },
      { kind: 'any', text: '⑧ 기술혁신형(이노비즈)·경영혁신형(메인비즈)·벤처기업의 자체 기술' },
      { kind: 'any', text: '⑨ 민관협력 오픈이노베이션(OI) 최종 선정 기술' },
      { kind: 'required', text: '제품 양산 후 3년 이내 기술(초격차 분야는 5년)' },
      { kind: 'required', text: '소상공인 아님(예외 분야 제외) · 융자제외 업종 아님 · 세금체납 없음' },
    ],
    criteria: { excludes_small_business: true, requires_any_tech_type: true },
    reapply_rule: { type: 'announcement', note: '1/5부터 예산 소진 시까지 매월 첫째 주 접수' },
    required_docs: ['사업자등록증명', '납세증명서(국세)', '지방세 납세증명서', '재무제표', '기술 증빙(특허증·인증서·R&D 완료 확인서·연구소 인정서 등)', '사업계획서'],
    exclusive_group: null,
    notes: '방식: 직접대출·대리대출·성장공유형·투자조건부·이차보전(홈페이지 기준). 특허·연구소·벤처인증 보유 고객에게 가장 직접적으로 열리는 중진공 자금.',
    sort_order: 220,
    active: true,
  },
  {
    key: 'kosme_export_starter',
    name: '중진공 신시장진출지원자금 (내수기업수출기업화)',
    institution: '중소벤처기업진흥공단',
    fund_type: '직접대출',
    limit_operating: 100000,
    limit_facility: null,
    cap_group: '중진공_60억',
    rate_note: '정책자금 기준금리(변동) 또는 고정금리',
    period_note: '운전 5년 이내(거치 2년)',
    eligibility_summary: '최근 1년 수출실적 10만불 미만 중소기업. **소상공인도 신청 가능(전체 소상공인)**. 운전자금 연간 10억.',
    conditions: [
      { kind: 'any', text: '① 수출 초보기업: 1불~10만불 미만 수출실적(최근 1년, 직·간접 합계)' },
      { kind: 'any', text: '② 정부·지자체 수출지원사업 참여기업(사업기간 또는 종료 후 1년 이내) 또는 수출 관련 지정제도 선정기업 — 수출바우처, 전자상거래수출지원 등' },
      { kind: 'any', text: '③ 기술수출 실적·계약 보유(특허·상표·디자인·노하우·기술서비스 등 무형자산 판매)' },
      { kind: 'any', text: '④ 해외법인 운영(설립 예정 포함)' },
      { kind: 'required', text: '융자제외 업종 아님 · 세금체납 없음 · 신용정보원 등록 없음' },
    ],
    criteria: { export_max_usd_exclusive: 100000, excludes_small_business: false },
    reapply_rule: { type: 'announcement', note: '1/5부터 예산 소진 시까지 매월 첫째 주 접수' },
    required_docs: ['사업자등록증명', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서', '수출실적증명원 또는 수출지원사업 참여 증빙', '사업계획서'],
    exclusive_group: null,
    notes: '소상공인 제외 규정(⑨)의 명시적 예외 — 소상공인 고객 중 소액이라도 수출(온라인 해외판매 포함)이 있으면 중진공 진입 경로가 됨. 우량기업 제한(①항) 적용 예외.',
    sort_order: 230,
    active: true,
  },
  {
    key: 'kosme_export_global',
    name: '중진공 신시장진출지원자금 (수출기업글로벌화)',
    institution: '중소벤처기업진흥공단',
    fund_type: '직접대출',
    limit_operating: 100000,
    limit_facility: 300000,
    cap_group: '중진공_60억',
    rate_note: '운전: 기준금리(변동) / 시설: 기준금리 − 0.3%p. 이차보전 방식은 최대 3%',
    period_note: '시설 10년 이내(거치 담보 4년·신용 3년) / 운전 5년 이내(거치 2년)',
    eligibility_summary: '최근 1년 수출실적 10만불 이상 중소기업(소상공인 포함). 연간 30억(운전 10억); 수출 고성장기업(전년 수출 100만$ 이상 + 3년 연평균 수출증가율 20%↑)은 60억.',
    conditions: [
      { kind: 'any', text: '① 수출 유망기업: 최근 1년 직·간접 수출실적 10만불 이상' },
      { kind: 'any', text: '② 해외법인 운영(설립 예정 포함)' },
      { kind: 'required', text: '융자제외 업종 아님 · 세금체납 없음 · 신용정보원 등록 없음' },
      { kind: 'bonus', text: '전년 수출 100만$ 이상 + 최근 3년 연평균 수출증가율 20% 이상 → 한도 60억' },
    ],
    criteria: { export_min_usd: 100000, excludes_small_business: false },
    reapply_rule: { type: 'announcement', note: '1/5부터 예산 소진 시까지 매월 첫째 주 접수' },
    required_docs: ['사업자등록증명', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서', '재무제표', '수출실적증명원', '사업계획서'],
    exclusive_group: null,
    notes: '사업장 건축·매입 용도 시설자금은 불가. 방식: 직접대출·성장공유형·이차보전.',
    sort_order: 240,
    active: true,
  },
  {
    key: 'kosme_growth_innovation',
    name: '중진공 혁신성장지원자금 (신성장기반, 일반)',
    institution: '중소벤처기업진흥공단',
    fund_type: '직접대출',
    limit_operating: 50000,
    limit_facility: 600000,
    cap_group: '중진공_60억',
    rate_note: '시설: 기준금리 + 0.2%p / 운전: 기준금리 + 0.5%p (국가핵심기술 보유기업은 기준금리). 이차보전은 최대 3%',
    period_note: '시설 10년 이내(거치 담보 4년·신용 3년) / 운전 5년 이내(거치 2년)',
    eligibility_summary: '업력 7년 이상 중소기업(창업자에 해당하지 않는 7년 미만 포함). 연간 60억(운전 5억). 운전자금은 시설 도입 초기 시운전자금 목적만 융자 가능 — 일반 운전자금은 이차보전(최근 3년 내 시설 도입 기업)으로.',
    conditions: [
      { kind: 'required', text: '업력 7년 이상 (또는 창업자 요건에 해당하지 않는 7년 미만 기업)' },
      { kind: 'required', text: '중소기업이며 소상공인 아님(예외 분야 제외)' },
      { kind: 'required', text: '융자제외 업종 아님 · 세금체납 없음 · 업종별 제한 부채비율 이내 · 3년 연속 이자보상배율 1.0 미만 한계기업 아님' },
      { kind: 'bonus', text: '지식서비스산업(참고6)·사회적경제기업·소부장 강소기업100·스타트업100·경쟁력강화위 추천·원전 협력기업은 시운전자금이 아닌 일반 운전자금(제품생산·시장개척)도 가능' },
      { kind: 'bonus', text: '스마트공장·디지털전환·탄소중립 투자(제조현장스마트화·Net-Zero 세부자금은 별도, 시설 100억 우대)' },
    ],
    criteria: { min_biz_age: 7, excludes_small_business: true },
    reapply_rule: { type: 'announcement', note: '1/5부터 예산 소진 시까지 매월 첫째 주 접수' },
    required_docs: ['사업자등록증명', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서', '재무제표(3개년)', '시설투자 계획·견적(시설자금 시)', '사업계획서'],
    exclusive_group: null,
    notes: '방식: 직접·대리·성장공유형·이차보전. 마일스톤자금의 업력 7년 이상 트랙. 세부자금(홈페이지 기준): 협동화 — 3개 이상 규합 협동화실천계획 또는 2개 이상 협업사업계획 승인, 연 100억(운전 15억), 시설 10년(거치 5)/운전 5년(2), 기준금리, 업력 제한 없음, 소상공인·부채비율 제한 예외 / Net-Zero 유망기업 — 그린분야·친환경 소재 전환·저탄소 설비 도입·탄소중립 컨설팅 선정 등, 연 60억(운전 5억), +0.5%p / 제조현장스마트화 — 스마트공장 지원사업 참여 또는 ICT 자동화 설비 도입, 연 100억(운전 10억), 기준금리 / 스케일업금융(P-CBO) — 회사채 60~120억, 신용평가 B+ 이상 외부감사 기업(별도 공고). 세부자금 운전자금은 시운전자금(시설자금의 50% 이내) 원칙.',
    sort_order: 250,
    active: true,
  },
  {
    key: 'kosme_restart',
    name: '중진공 재창업자금 (재도약지원)',
    institution: '중소벤처기업진흥공단',
    fund_type: '직접대출',
    limit_operating: 50000,
    limit_facility: 600000,
    cap_group: '중진공_60억',
    rate_note: '정책자금 기준금리(변동). 성실경영 심층평가 통과기업은 − 0.3%p',
    period_note: '시설 10년 이내(거치 4년) / 운전 6년 이내(거치 3년)',
    eligibility_summary: '중소기업을 폐업하고 새로 설립한 업력 7년 미만(신산업 10년) 재창업기업 또는 예비재창업자. 자금조달 애로 또는 신용회복 공공정보 등록자 + 성실경영평가 통과. 연간 60억(운전 5억; 심층평가 통과 시 10억). 소진공 재도전특별자금의 중진공 버전.',
    conditions: [
      { kind: 'required', text: '폐업 이력 보유(폐업 완료)한 자가 현재 재창업기업의 대표(개인기업 대표 / 법인 대표이사·실질기업주). 폐업 업종이 유흥주점·금융보험·부동산·공공행정 등이면 제외' },
      { kind: 'required', text: '재창업 업력 7년 미만(신산업 창업 분야 10년 이내). 설립 7년 미만 법인 인수도 포함' },
      { kind: 'any', text: '자금조달에 애로를 겪고 있는 기업인' },
      { kind: 'any', text: '신용정보원 공공정보(파산면책·회생인가·신용회복확정·채무조정확정 등) 등록자 → 신복위 접수 경로(별도 기준)' },
      { kind: 'required', text: '중소기업창업 지원법상 성실경영평가 통과 (재창업 전 기업을 분식회계·고의부도·부당해고 없이 성실히 경영했는지 평가)' },
      { kind: 'required', text: '재창업 준비 중인 자는 지원결정 후 3개월 이내 사업자등록 가능해야 함' },
      { kind: 'required', text: '신용미회복자(신용회복절차 정상 진행 중 제외)는 총부채 30억 이하' },
      { kind: 'bonus', text: '재도전성공패키지·TIPS-R·정부 R&D 선정, 특허·실용신안·기업부설연구소 보유 재창업, 재도전Fund 투자유치, ICT 재창업 선정, 혁신성장분야·소부장 영위 → 우선 접수 + 융자상환금조정형(5억 이내) 신청 가능' },
      { kind: 'bonus', text: '성실경영 심층평가 통과 → 금리 −0.3%p, 운전 한도 10억' },
    ],
    criteria: { max_biz_age_exclusive: 7, requires_closure_history: true, excludes_small_business: true },
    reapply_rule: { type: 'announcement', note: '재도약지원자금은 수시 접수 가능. 업력 1년 미만은 역량평가 + 초기재창업심의위원회' },
    required_docs: ['사업자등록증명', '폐업사실증명(과거 사업자)', '납세증명서(국세)', '지방세 납세증명서', '재무제표(해당 시)', '성실경영평가 결과', '사업계획서'],
    exclusive_group: null,
    notes: '융자제한 ⑪(한계기업)·⑬(200억 초과)·⑮(5년 3회) 적용 예외, ③(세금체납)은 압류·매각 유예 시 예외. 신복위 재창업지원은 모든 채무가 조정되어 연체 정보가 해제된 경우에 한함(중진공·신보·기보 평가 → 재창업지원위원회 심의). 방식: 직접·대리대출(신복위·융자상환금조정형은 직접대출). 폐업사실증명 API(CODEF, 9월 예정)와 연결되는 자금.',
    sort_order: 260,
    active: true,
  },
  {
    key: 'kosme_emergency_hardship',
    name: '중진공 긴급경영안정자금 (일시적경영애로)',
    institution: '중소벤처기업진흥공단',
    fund_type: '직접대출',
    limit_operating: 100000,
    limit_facility: null,
    cap_group: '중진공_60억',
    rate_note: '정책자금 기준금리(변동) + 0.5%p (홈플러스 피해기업은 기준금리)',
    period_note: '운전 5년 이내(거치 2년)',
    eligibility_summary: '정해진 경영애로 사유(거래처 도산, 화재 등 대형사고, 산업구조조정 업종, 불공정거래·기술침해 피해, 고용·산업위기지역, 원자재 급등, 보호무역·중동전쟁 피해 등)로 매출 또는 영업이익이 10% 이상 감소(직전연도 vs 직전전연도)했거나 대형사고 피해 1억 이상인 기업 중 경영정상화 가능성이 큰 기업. 피해 발생 후 6개월 이내 신청. 운전 10억(3년간 15억).',
    conditions: [
      { kind: 'required', text: '① 경영애로 사유가 공고에 열거된 것 중 하나 — 단순 시장성 부족·영업부진은 제외' },
      { kind: 'any', text: '② 매출액 또는 영업이익 10% 이상 감소 (직전연도 vs 직전전연도)' },
      { kind: 'any', text: '② 대형사고(화재 등) 피해 규모 1억원 이상' },
      { kind: 'required', text: '③ 경영애로 피해 발생(비교 가능 시점) 후 6개월 이내 신청 (산업구조조정 업종은 1년)' },
      { kind: 'required', text: '소상공인 아님(예외 분야 제외) · 융자제외 업종 아님' },
    ],
    criteria: { requires_hardship_reason: true, decline_pct_min: 10, excludes_small_business: true },
    reapply_rule: { type: 'announcement', note: '수시 접수. 5년 3회 제한·200억 제한 적용 예외. 부채비율 초과기업 예외' },
    required_docs: ['사업자등록증명', '부가세과세표준증명(매출 감소 증빙)', '재무제표(직전·직전전연도)', '납세증명서(국세)', '지방세 납세증명서', '경영애로 사유 증빙(거래처 도산 서류, 화재 확인서 등)'],
    exclusive_group: null,
    notes: '소진공 일시적경영애로자금(연매출 1억400만 미만·15% 감소)과 이름은 같지만 대상·기준이 다름 — 중진공은 사유가 열거된 것이어야 하고 10% 감소.',
    sort_order: 270,
    active: true,
  },
  {
    key: 'kosme_emergency_disaster',
    name: '중진공 긴급경영안정자금 (재해중소기업)',
    institution: '중소벤처기업진흥공단',
    fund_type: '직접대출',
    limit_operating: 100000,
    limit_facility: null,
    cap_group: '중진공_60억',
    rate_note: '1.9% 고정금리',
    period_note: '운전 5년 이내(거치 2년)',
    eligibility_summary: '자연재난·사회재난 피해 중소기업 — 시장·군수·구청장이 발급한 「재해중소기업 확인증」 제출. 피해금액 이내 최대 10억(3년간 15억). 용도는 직접 피해 복구 비용(시설 복구 포함).',
    conditions: [
      { kind: 'required', text: '재해중소기업 확인증(시장·군수·구청장 발급) 보유' },
      { kind: 'required', text: '융자제외 업종 아님' },
    ],
    criteria: { requires_disaster_certificate: true },
    reapply_rule: { type: 'announcement', note: '수시 접수. 우량기업·휴폐업(재해로 인한 휴업)·세금체납(압류 유예)·부채비율 제한 적용 예외' },
    required_docs: ['재해중소기업 확인증', '사업자등록증명', '피해 규모 증빙', '납세증명서(국세)', '지방세 납세증명서'],
    exclusive_group: null,
    notes: '고정금리 자금이라 우대금리 가감 없음.',
    sort_order: 280,
    active: true,
  },
  {
    key: 'kosme_milestone',
    name: '중진공 마일스톤자금 (소진공 → 중진공 졸업 소상공인)',
    institution: '중소벤처기업진흥공단',
    fund_type: '직접대출',
    limit_operating: 80000,
    limit_facility: null,
    cap_group: '중진공_60억',
    rate_note: '창업기반지원(7년 미만) 또는 혁신성장지원(7년 이상) 자금 조건과 동일',
    period_note: '3개년 총 한도 설정 → 1차년도 50%, 2차 30%, 3차 20% (2·3차는 성과 달성 시)',
    eligibility_summary: '소진공에서 혁신성장촉진자금 지원(25~26년)·강한소상공인 선정(22~25년)·LIPS Ⅰ/Ⅱ 지원을 받은 소상공인 중, 신청 전 3개월 평균 고용인원이 소상공인 기준을 초과해 사실상 소기업으로 성장한 기업. 3개년 총 최대 8억(운전자금). 소상공인 고객이 성장했을 때 중진공으로 올라가는 다리.',
    conditions: [
      { kind: 'any', text: '소진공 혁신성장촉진자금을 지원받은 소상공인 졸업후보기업(25~26년)' },
      { kind: 'any', text: '강한 소상공인 성장지원 사업 선정기업(22~25년)' },
      { kind: 'any', text: '민간투자연계형 매칭융자(LIPS Ⅰ, 23~25년) 또는 혁신소상공인 투자연계지원(LIPS Ⅱ, 25~26년) 지원기업' },
      { kind: 'required', text: '신청 전 3개월 평균 고용인원이 소기업 기준 충족 (광업·제조·건설·운수 10명 이상, 기타 업종 5명 이상)' },
      { kind: 'required', text: '2·3차년도 추가대출: 매출 또는 고용 중 하나가 연평균 20% 이상 성장 + 실질기업주 변경·자본잠식·고용 미달 아님' },
    ],
    criteria: { requires_sojinkong_graduate: true, min_employees_by_industry: { '광업·제조·건설·운수': 10, '기타': 5 } },
    reapply_rule: { type: 'announcement', note: '1차년도 신청·평가 후 2·3차년도는 각 연도 3분기에 일괄 접수' },
    required_docs: ['소진공 지원 이력 증빙(혁신성장촉진자금 대출 내역 등)', '고용보험 가입자명부(3개월)', '사업자등록증명', '재무제표', '납세증명서(국세)', '지방세 납세증명서'],
    exclusive_group: null,
    notes: '소상공인 제외 규정(⑨)의 명시적 예외. 혁신성장촉진자금 받은 고객이 직원을 늘려 소기업이 되면 바로 안내할 자금.',
    sort_order: 290,
    active: true,
  },
  {
    key: 'kosme_business_conversion',
    name: '중진공 사업전환자금 (일반)',
    institution: '중소벤처기업진흥공단',
    fund_type: '직접대출',
    limit_operating: 50000,
    limit_facility: 1000000,
    cap_group: '중진공_60억',
    rate_note: '운전: 기준금리(변동) / 시설: 기준금리 − 0.3%p',
    period_note: '시설 10년 이내(거치 담보 5년·신용 4년) / 운전 6년 이내(거치 3년)',
    eligibility_summary: '중소기업 사업전환 촉진에 관한 특별법에 따라 사업전환계획(또는 공동사업전환계획) 승인을 받은 기업으로 승인일로부터 5년 미만. 상시근로자 5인 이상. 연간 100억(운전 5억).',
    conditions: [
      { kind: 'required', text: '사업전환계획·공동사업전환계획 승인(업종전환·업종추가 등 타당성 평가 통과) 후 5년 미만. 승인 신청 요건: 3년 이상 계속 영위 + 상시근로자 5인 이상, 전환 진출업종은 제조업 또는 서비스업(융자제외 업종 제외)' },
      { kind: 'required', text: '승인 제외 아님: 승인 탈락·취소 6개월 미경과, 휴폐업 중, 신업종 최초 매출발생 1년 이상 경과(시제품·내부용 5% 이내는 미간주)' },
      { kind: 'bonus', text: '수출향상(최근 1년 직수출 50만불↑·20%↑)·최근 1년 10인 이상 고용창출·최근 1년 20억 이상 시설투자 기업은 운전자금 연 10억' },
      { kind: 'required', text: '융자제외 업종 아님 · 세금체납 없음' },
    ],
    criteria: { min_employees: 5, requires_conversion_plan_approval: true },
    reapply_rule: { type: 'announcement', note: '재도약지원자금은 수시 접수 가능' },
    required_docs: ['사업전환계획 승인서', '사업자등록증명', '재무제표', '납세증명서(국세)', '지방세 납세증명서', '4대보험 가입자명부'],
    exclusive_group: null,
    notes: '성공 기준: 이행기간 중 신규업종 매출 또는 종업원이 전체의 30% 이상. 실시기간 승인일부터 3년(1회 1년 연장). 세부: 사업재편·통상변화대응 트랙은 별도(통상변화대응 자료는 아직 미수신). 소상공인 고객에겐 거의 해당 없어 기본 비활성.',
    sort_order: 300,
    active: false,
  },
  {
    key: 'kosme_restructuring',
    name: '중진공 구조개선전용자금',
    institution: '중소벤처기업진흥공단',
    fund_type: '직접대출',
    limit_operating: 100000,
    limit_facility: null,
    cap_group: '중진공_60억',
    rate_note: '일반: 정책자금 기준금리(변동) / 선제적 자율구조개선: 2.5% 고정',
    period_note: '운전 5년 이내(거치 2년)',
    eligibility_summary: '위기징후 중소기업의 조기 정상화·재도약용. ① 진로제시컨설팅(기초진로제시)에서 구조개선 대상 판정 ② 캠코 협업 금융지원 추천(패키지형 회생, 국세 물납 법인, Sales&LeaseBack) ③ 선제적 자율구조개선 프로그램 지원 결정 기업. 3년간 10억 이내 운전자금(선제적 자율구조개선은 15억).',
    conditions: [
      { kind: 'any', text: '① 정책금융기관(중진공·신보·기보·테크노파크) 지정 부실징후기업, 워크아웃·회생계획 정상 이행 중, 기타 경영애로로 진로제시가 필요한 기업이 진로제시컨설팅을 받고 구조개선 대상으로 판정 (컨설팅 비용의 10%+부가세 기업 부담)' },
      { kind: 'any', text: '② 캠코 협업 금융지원 추천: 패키지형 회생기업 금융지원 참여, 국세 물납 법인, Sales & LeaseBack 참여기업' },
      { kind: 'any', text: '③ 선제적 자율구조개선 프로그램(중진공+협약은행 공동 금융지원·경영개선계획) 지원 결정 기업' },
    ],
    criteria: { requires_restructuring_designation: true },
    reapply_rule: { type: 'announcement', note: '2026-01-02부터 예산 소진 시까지 관할 지역본부 접수. 별도 융자절차(사업계획 → 상담·신청 → 서류·현장실사 → 평가·승인 → 지원결정 → 실행)' },
    required_docs: ['진로제시컨설팅 결과 또는 캠코 추천서 또는 자율구조개선 지원결정서', '사업자등록증명', '재무제표', '납세증명서(국세)', '지방세 납세증명서'],
    exclusive_group: null,
    notes: '소상공인 고객엔 거의 해당 없어 기본 비활성. 선제적 자율구조개선 프로그램 세부 자료는 아직 미수신.',
    sort_order: 310,
    active: false,
  },
]

// 자금 하나에 속하지 않는 공통 규칙. 자격 판정 엔진과 AI 상담 프롬프트가 함께 참조.
export const SEED_COMMON_RULES = [
  {
    key: 'small_business_employee_limit',
    title: '소상공인 기준 (직원 수)',
    content: '대표자 제외 4대보험 가입 직원 기준. 제조·건설·운수·광업: 9명 이하. 그 외(도소매·음식점·서비스 등): 4명 이하. 기준 초과 시 정책자금 신청 불가.',
    params: { limits: { '제조·건설·운수·광업': 9, '그 외': 4 } },
    sort_order: 10,
  },
  {
    key: 'debt_over_sales',
    title: '매출초과차입금 기준',
    content: '업력 7년 미만: 적용 안 함 (대출이 매출보다 많아도 가능). 업력 7년 이상: 연매출 - 사업자대출 잔액 합계가 마이너스면 신청 불가. 사업자대출 = 소진공 + 재단 + 신보 + 기보 + 중진공 + 사업자명의대출 (아파트담보·개인신용대출은 제외).',
    params: { applies_from_biz_age: 7 },
    sort_order: 20,
  },
  {
    key: 'sojinkong_total_cap',
    title: '소진공 직접대출 총한도',
    content: '기본 총한도 1억원 (직접대출 잔액 합산). 혁신형·도약형은 총한도 2억원 별도 적용. 남은 한도 = 총한도 - 현재 소진공 직접대출 잔액. 신용취약소상공인자금은 자금 자체 한도 3천만원(잔액 합산) 별도.',
    params: { cap_groups: { '소진공_기본_1억': 10000, '소진공_확장_2억': 20000, '신용취약_3천': 3000, '재단_1억': 10000, '중진공_60억': 600000 } },
    sort_order: 30,
  },
  {
    key: 'guarantee_exclusive',
    title: '보증기관 조합 규칙 (재단·신보·기보)',
    content: '① 신보 ↔ 기보: 무조건 동시 이용 불가. 하나를 쓰고 있으면 다 갚고 오거나, 다른 기관이 갚아주고 추가대출(대환)하는 형태만 가능 — 하나 쓰고 있으면 상대적으로 받기 매우 어렵다. ② 기보 ↔ 재단: 공동 보유 불가. 재단 쓰고 있으면 기보가 안 해줄 때가 많지만, 규모·기술·특허·경력이 모두 좋으면 기보가 재단 대출을 갚아주고 추가대출하는 경우 있음. ③ 신보 ↔ 재단: 같은 "신용보증" 계열. 원칙적으로 도매·큰 기업 → 신용보증기금, 소매·요식 → 신용보증재단인데, "도소매업"으로 묶인 사업자는 둘 다 가능. 기금 쓰고 있어도 재단에서 추가로 해주는 경우가 있음(매출 17억 대표: 신보 3억 + 재단 1억). ④ 평가 축: 신보는 신용·재무, 기보는 기술·특허·인증·경력 등 비재무까지. ⑤ 업종은 거의 장벽이 아님 — 제조·도소매·IT·건설·서비스 등은 자격(직원 수 등)·매출·재무제표만 되면 재단·기금 모두 검토. 유일한 업종 예외는 비프랜차이즈 요식업(프랜차이즈는 가능). 기보는 비재무(기술·특허·연구소·경력)를 재무보다 더 많이 봄. 대환은 복잡하므로 대표에게 보고 후 진행.',
    params: { exclusive_group: '보증기관' },
    sort_order: 40,
  },
  {
    key: 'sojinkong_one_at_a_time',
    title: '소진공 직접대출은 한 번에 1개만',
    content: '소진공 직접대출은 심사 결과가 나올 때까지 한 번에 1개 자금만 접수 가능 (일시적경영애로자금뿐 아니라 모든 직접대출 공통). 대리대출(보증서·확인서 기반으로 은행에서 실행하는 방식)은 별개라 직접대출과 병행 가능.',
    params: { exclusive_group: '소진공_직접대출' },
    sort_order: 45,
  },
  {
    key: 'direct_plus_guarantee',
    title: '직접대출 + 보증 동시진행',
    content: '소진공 직접대출(직접)과 재단·신보·기보(간접/보증)는 서로 다른 방식이라 타이밍만 맞으면 함께 진행 가능. 순서: ① 소진공 직접대출 접수 → ② 보증기관 접수 → ③ 보증서 수령 후 대기 → ④ 소진공 심사 완료 후 약정·입금 → ⑤ 보증서 들고 은행 방문하여 보증대출 실행.',
    params: {},
    sort_order: 50,
  },
  {
    key: 'tax_delinquency',
    title: '체납',
    content: '국세·지방세 체납 중이면 정책자금 신청 불가 (체납 해소 후 신청 가능).',
    params: {},
    sort_order: 60,
  },
  {
    key: 'bonus_points',
    title: '가점 요소 (기관별로 다름)',
    content: '소진공: 노란우산공제, 여성기업확인서, 직접대출 성실상환 이력, 특허보유. 중진공·신보·기보: 기업부설연구소, 벤처인증. 기관별로 다르므로 섞어서 안내하지 않음.',
    params: { 소진공: ['노란우산공제', '여성기업확인서', '직접대출 성실상환 이력', '특허보유'], '중진공·신보·기보': ['기업부설연구소', '벤처인증'] },
    sort_order: 70,
  },
  {
    key: 'jungjingong_general',
    title: '중진공 공통 특성 및 융자제한 (2026 공고 기준)',
    content: '[근거: 2026년 중소기업 정책자금 융자계획 변경공고 제2026-464호, docs/knowledge/kosme-2026/] ① 대상은 중소기업기본법상 중소기업 — 소상공인 규모를 넘어도 되고 매출 규모가 클수록 유리. ② 소상공인은 원칙 제외(유의사항 ⑨; 소상공인 기준: 광업·제조·건설·운수 상시근로자 10명 미만, 그 외 5명 미만). 예외: 혁신성장·초격차·신산업 분야 소상공인, 중점지원분야(참고1~4) 소상공인의 청년전용창업자금, 신시장진출지원자금은 전체 소상공인 가능, (예비)사회적기업·협동조합·마을기업·자활기업·소셜벤처 소상공인, 소상공인 유예기업, 마일스톤자금 신청 소상공인. ③ 융자제외 업종(별표1): 주점업(5621), 부동산업, 금융·보험업, 법무·회계·세무, 보건업, 초중고·입시교육, 사행성·유흥, 협회·단체, 다단계 등. 일반 음식점은 제외 업종이 아님 — 요식업이 실제로 못 받는 건 소상공인 제외 규정·부채비율(숙박음식 제한 500%)·심사 때문이며 대표 경험상 요식업 수령 사례 없음. ④ 기타 제한: 세금체납, 휴폐업, 신용정보원 연체·부도·회생 등 등록, 업종별 제한 부채비율 초과(제조 340%·도소매 393%·숙박음식 500% 등; 간편장부대상자는 예외), 업력 5년 초과 한계기업(3년 연속 이자보상배율 1.0 미만; 재창업자금은 예외), 기업평가 탈락·전액 포기 후 6개월, 최근 5년 정책자금 3회 이상(재도약·긴급경영안정·이차보전 등 제외; 시설자금·성과창출기업은 추가 1회), 정부·지자체 융자·보증 5년 200억 초과, 중진공 운전자금 누적 25억 초과 시 운전자금 제외. ⑤ 한도: 기업당 60억(대출 잔액+신규 합산), 지방소재 70억, 사업별 우대·정부정책 우대 100억. ⑥ 금리: 정책자금 기준금리(분기별 변동) ± 자금별 가감. 우대금리(합산 최대 0.4%p): 유망기업 0.1, 정책연계(신보 매출채권보험, 창업기반지원 운전) 0.1, 포용금융(사회적경제·여성·장애인기업) 0.1, 시설자금 0.3, 성실경영(재창업) 0.3, 성과창출(고용 10인↑·수출 50만불&20%↑·매출 30억&연 20%↑) 각 0.1 최대 0.3, 투자연계 0.3. 고정금리 자금(청년전용 2.5%, 재해 1.9%, 구조개선전용 2.5%)은 우대 제외. 융자신청서 제출 시 우대금리 신청 필수. ⑦ 신청: 2026-01-05부터 예산 소진 시까지 매월 첫째 주 온라인(중진공 누리집 디지털지점). 재도약지원·재해는 수시. 절차: 기업정보 입력 → 정책우선도 평가(심사기회 부여 여부) → 융자신청·서류 제출 → 기업평가(현장/비대면; 기술성·사업성·미래성장성·경영능력·사업계획 타당성) → 융자결정 → 대출실행 → 사후관리. 지원금액은 평가등급·매출·기대출·재무·상환능력을 종합해 한도 내 산출, 감액 가능. 정책자금 내비게이션(업력·수출·용도 입력)으로 적합자금 자동 추천. ⑧ 방식: 직접대출, 대리대출(은행), 이차보전(은행 대출 이자 보전, 최대 3%), 성장공유형·투자조건부(투융자). ⑨ 6대 자금: 혁신창업사업화(창업기반지원·청년전용·개발기술사업화), 신시장진출지원(내수→수출·수출글로벌화), 신성장기반(혁신성장지원·협동화·제조현장스마트화·Net-Zero·스케일업), 재도약지원(사업전환·구조개선·재창업), 긴급경영안정(재해·일시적경영애로), 밸류체인안정화(동반성장네트워크론·매출채권팩토링). ⑩ 서류: 납세증명서 등 대부분 데이터 자동 연계로 제출 불필요, 융자 신청서와 일부 증빙만. ⑪ 컨설팅사 부당개입(직원 사칭, 보험계약 강요 등) 신고 대상 — 신청서 작성 대행은 정책자금 지원과 무관하며 부당개입 의심 시 융자 취소·3년 제한.',
    params: { total_cap: 600000, total_cap_regional: 700000, total_cap_preferred: 1000000, youth_age_max: 39, small_business_threshold: { '광업·제조·건설·운수': 10, '기타': 5 }, debt_ratio_limit: { '제조업': 340.2, '도매및소매업': 393.0, '숙박및음식점업': 500.0, '정보통신업': 425.7, '건설업': 329.1 } },
    sort_order: 75,
  },
  {
    key: 'application_philosophy',
    title: '자금 판정의 기본 철학 — 정답 맞추기가 아니라 접수하게 하기',
    content: '정책자금은 딱 떨어지는 정답이 없다. 중진공은 직원 5명 이상, 소진공은 요식업 직원 5명 미만처럼 기준과 매출에 따라 갈리는 경계선만 있을 뿐이다. 기준을 학습하는 목적은 정답을 맞추는 게 아니라 "맞는 기관에 접수라도 하게 하는 것" — 접수하면 담당자가 더 맞는 자금이 있으면 알아서 매칭해준다. 결국 이것도 대출이라 최종 결정은 기존 부채·매출·재무제표·신용점수 4가지로 난다. 따라서 툴은 가능/불가로 자르지 말고 "어느 기관에 어떤 자금으로 접수를 넣을 수 있는가 + 근거 + 부채·매출·재무·신용 상태"를 보여주고, 컨설턴트가 접수를 아예 안 넣는 실수를 막는 방향으로 판정한다.',
    params: { decision_factors: ['기존 부채', '매출', '재무제표', '신용점수'], output_style: '접수 후보 + 근거 (binary 판정 지양)' },
    sort_order: 78,
  },
  {
    key: 'consult_principles',
    title: '상담 원칙',
    content: '정보가 없으면 단정짓지 말고 먼저 물어본다. "해당 없음"처럼 소극적으로 끝내지 않고 항상 받을 수 있는 최대 금액을 찾는다. 분석 순서: 직원 수 → 매출초과차입금 → 소진공 잔여한도 → 혁신성장촉진 → 재도전특별 → 재단 동시진행 → 신보/기보 → 최종 진행 순서·예상 총액 정리.',
    params: {},
    sort_order: 80,
  },
]
