// lib/policyFundsSeed.js
// 정책자금 마스터 DB의 초기 데이터.
// 출처: app/api/chat/route.js(AI 상담 시스템 프롬프트), lib/policyFundAnalysis.js, lib/policyFundEstimate.js,
//       app/components/PolicyFundAnalyzer.jsx — 2026-09-02 기준으로 거기 있던 지식을 하나도 빼지 않고 구조화한 것.
// 이 파일은 "DB가 비어있을 때 최초 1회" 채우는 용도. 이후 수정은 /admin/policy-funds 관리자 화면에서 하고,
// 이 파일은 백업/참고용으로만 남겨둠 (관리자 화면에서 고친 내용이 이 파일에 자동 반영되지는 않음).
//
// 금액 단위: 전부 만원.
//
// SEED_VERSION: 이 파일을 고칠 때마다 올린다. lib/policyFundsStore.js가 배포 후 첫 호출 때 버전이 바뀐 걸 보고
//   DB의 시드 항목을 갱신함. 단, 관리자 화면에서 직접 고친 항목(updated_by가 'seed'가 아닌 것)은 덮어쓰지 않음.
//   → 대표가 말로 알려준 수정사항은 Claude가 이 파일에 반영 + 버전 올림 → 배포되면 자동 적용. 이게 기본 흐름.
//
// conditions: [{ text, kind }] — kind는 'required'(전부 충족) / 'any'(any끼리 묶어서 그중 1개만) / 'bonus'(가점 — 없어도 신청 가능)
// reapply_rule: { type: 'none' | 'months' | 'announcement', months, months_by_region: {수도권, 지방}, note }
//   - months: 마지막 수령일 기준 재신청 가능까지 개월 수
//   - announcement: 제한기간은 없지만 공고가 떠야 신청 가능 (소진공) → 부결 고객은 공고 알림과 연결
// criteria: 자격 자동판정 엔진이 읽는 수치/플래그 (선택). 없는 키는 판정에서 무시.

export const SEED_VERSION = '2026-09-02.2'

export const SEED_FUNDS = [
  // ───────────────────────── 소진공 직접대출 ─────────────────────────
  {
    key: 'sojinkong_hyuksin_general',
    name: '혁신성장촉진자금 일반형',
    institution: '소상공인시장진흥공단',
    fund_type: '직접대출',
    limit_operating: 10000,
    limit_facility: 50000,
    cap_group: '소진공_기본_1억',
    rate_note: '정책자금 기준금리 + 0.4%p',
    period_note: '운전 5년 (거치 2년) / 시설 8년 (거치 3년)',
    eligibility_summary: '아래 스마트기기 중 1개 이상을 도입·운영 중인 소상공인. 소진공 직접대출 총한도 1억(잔액 합산) 안에서 신청.',
    conditions: [
      { kind: 'required', text: '스마트기기 1개 이상 도입·운영 중 (아래 목록 참고)' },
      { kind: 'required', text: '소진공 직접대출 잔여한도 있음 (총한도 1억 - 현재 잔액)' },
    ],
    smart_devices: [
      '3D 풋스캐너 / 3D 프린터',
      'AI CCTV / AI 두피분석 / AI 안면인식',
      'AI·IOT 온도관리시스템',
      '주문·예약·결제 키오스크',
      'QR/NFC 오더 / 테이블 오더',
      'AI·무게형·모듈형 무인판매기',
      '서빙로봇 / 헬퍼로봇 / 조리로봇',
      '디지털광고보드 / 디지털메뉴보드',
      '고객관리·예약·매출분석·재고관리 S/W',
      '온라인예약관리 / 매장멤버십관리시스템',
      '축산 육가공공정시스템',
    ],
    criteria: { requires_smart_device: true },
    reapply_rule: { type: 'announcement', note: '재신청 제한기간 없음. 공고가 떠야 신청 가능 — 부결 시 다음 공고 알림과 연결' },
    required_docs: ['사업자등록증명', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서', '스마트기기 도입 증빙(구매계약서·영수증·사진 등)'],
    exclusive_group: '소진공_직접대출', // 소진공 직접대출은 결과 나올 때까지 한 번에 1개만 접수 가능,
    notes: '2026년 4월부터 스마트기기 목록에서 배달앱·자동화기기 삭제됨.',
    sort_order: 10,
  },
  {
    key: 'sojinkong_hyuksin_innovative',
    name: '혁신성장촉진자금 혁신형',
    institution: '소상공인시장진흥공단',
    fund_type: '직접대출',
    limit_operating: 20000,
    limit_facility: 100000,
    cap_group: '소진공_확장_2억',
    rate_note: '정책자금 기준금리 + 0.4%p',
    period_note: '운전 5년 (거치 2년) / 시설 8년 (거치 3년)',
    eligibility_summary: '일반형 요건(스마트기기)을 충족하면서 아래 성장 요건 중 1개 이상 해당. 총한도 2억 별도 적용.',
    conditions: [
      { kind: 'required', text: '스마트기기 1개 이상 도입·운영 중 (일반형 요건)' },
      { kind: 'any', text: '최근 1년 수출 실적 1천달러 이상 (수출실적증명원 발급 가능)' },
      { kind: 'any', text: '23년→24년, 24년→25년 매출 연속 10% 이상 증가 (단 23년 매출 5천만원 이상)' },
      { kind: 'any', text: '소진공 직접대출 원금분할상환 중 또는 최근 3년 내 완제 (거치기간 중이면 해당 안 됨)' },
      { kind: 'any', text: '스마트공장 도입 / 강한소상공인·로컬크리에이터 선정' },
    ],
    criteria: { requires_smart_device: true, credit_min_recommended: 700 },
    reapply_rule: { type: 'announcement', note: '재신청 제한기간 없음. 공고가 떠야 신청 가능' },
    required_docs: ['사업자등록증명', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서', '재무제표(복식부기 대상자)', '수출실적증명원 또는 매출 증가 증빙 등 해당 요건 증빙'],
    exclusive_group: '소진공_직접대출', // 소진공 직접대출은 결과 나올 때까지 한 번에 1개만 접수 가능,
    notes: '신용점수 공식 제한 없으나 실전 기준 700점 이상 권장.',
    sort_order: 20,
  },
  {
    key: 'sojinkong_jaedo_general',
    name: '재도전특별자금 일반형',
    institution: '소상공인시장진흥공단',
    fund_type: '직접대출',
    limit_operating: 7000,
    limit_facility: null,
    cap_group: '소진공_기본_1억',
    rate_note: '정책자금 기준금리 + 0.4%p',
    period_note: '운전 5년 (거치 2년) / 시설 8년 (거치 3년)',
    eligibility_summary: '현재 사업자 1개 + 업력 7년 미만이면서, 폐업이력 등 재도전 사유가 있는 소상공인.',
    conditions: [
      { kind: 'required', text: '현재 대표자 명의 사업자 1개 (2개 이상이면 불가)' },
      { kind: 'required', text: '업력 7년 미만' },
      { kind: 'any', text: '과거 폐업 이력 있음' },
      { kind: 'any', text: '업종 전환 이력 있음' },
      { kind: 'any', text: '3개월 이상 휴업 이력 있음' },
      { kind: 'any', text: '매출 감소로 사업장 이전 이력 있음' },
    ],
    criteria: { max_biz_age_exclusive: 7, current_biz_count: 1, requires_closure_or_restart_history: true },
    reapply_rule: { type: 'announcement', note: '재신청 제한기간 없음. 공고가 떠야 신청 가능' },
    required_docs: ['사업자등록증명', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서', '폐업사실증명(폐업이력 증빙) 또는 해당 사유 증빙'],
    exclusive_group: '소진공_직접대출', // 소진공 직접대출은 결과 나올 때까지 한 번에 1개만 접수 가능,
    notes: '폐업사실증명 API는 CODEF에서 2026년 9월 중 제공 예정.',
    sort_order: 30,
  },
  {
    key: 'sojinkong_jaedo_leap',
    name: '재도전특별자금 도약형',
    institution: '소상공인시장진흥공단',
    fund_type: '직접대출',
    limit_operating: 20000,
    limit_facility: null,
    cap_group: '소진공_확장_2억',
    rate_note: '정책자금 기준금리 + 0.4%p',
    period_note: '운전 5년 (거치 2년) / 시설 8년 (거치 3년)',
    eligibility_summary: '재창업 업력 2~7년 + 소진공 성실상환 + 성장 요건 중 1개.',
    conditions: [
      { kind: 'required', text: '재창업 업력 2년 이상 7년 미만' },
      { kind: 'required', text: '소진공 직접대출 성실상환 (원금분할상환 중)' },
      { kind: 'any', text: '직원 2명 이상' },
      { kind: 'any', text: '24년→25년 매출 5% 이상 증가' },
      { kind: 'any', text: '최근 6개월 vs 이전 6개월 매출 5% 이상 증가' },
    ],
    criteria: { min_biz_age: 2, max_biz_age_exclusive: 7, requires_sojinkong_good_repayment: true },
    reapply_rule: { type: 'announcement', note: '재신청 제한기간 없음. 공고가 떠야 신청 가능' },
    required_docs: ['사업자등록증명', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서', '재무제표(복식부기 대상자)', '4대보험 가입자명부(직원 요건 시)'],
    exclusive_group: '소진공_직접대출', // 소진공 직접대출은 결과 나올 때까지 한 번에 1개만 접수 가능,
    notes: null,
    sort_order: 40,
  },
  {
    key: 'sojinkong_credit_vulnerable',
    name: '신용취약소상공인자금',
    institution: '소상공인시장진흥공단',
    fund_type: '직접대출',
    limit_operating: 3000,
    limit_facility: null,
    cap_group: '신용취약_3천',
    rate_note: '정책자금 기준금리 + 0.4%p',
    period_note: '5년 (거치 2년)',
    eligibility_summary: 'NICE 신용점수 595~839점 구간 + 국세·지방세 체납 없음 + 연체 없음. 자금 자체 한도 3천만원(잔액 합산).',
    conditions: [
      { kind: 'required', text: 'NICE 신용점수 595점 이상 839점 이하' },
      { kind: 'required', text: '국세·지방세 체납 없음' },
      { kind: 'required', text: '금융권 연체 없음' },
      { kind: 'required', text: '이 자금 잔여한도 있음 (3천만원 - 기존 신용취약자금 잔액)' },
    ],
    criteria: { credit_min: 595, credit_max: 839, no_tax_delinquency: true, no_overdue: true },
    reapply_rule: { type: 'announcement', note: '재신청 제한기간 없음. 공고가 떠야 신청 가능' },
    required_docs: ['사업자등록증명', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서'],
    exclusive_group: '소진공_직접대출', // 소진공 직접대출은 결과 나올 때까지 한 번에 1개만 접수 가능,
    notes: '신용점수 839점 초과면 대상 범위 초과, 595점 미달이면 최저 기준 미달.',
    sort_order: 50,
  },
  {
    key: 'sojinkong_temporary_hardship',
    name: '일시적경영애로자금',
    institution: '소상공인시장진흥공단',
    fund_type: '직접대출',
    limit_operating: 7000,
    limit_facility: null,
    cap_group: '소진공_기본_1억',
    rate_note: '정책자금 기준금리 + 0.4%p',
    period_note: '운전 5년 (거치 2년)',
    eligibility_summary: '연매출 1억 400만원 미만 + 업력 7년 미만 + 매출 15% 이상 감소(연간·반기·분기 등 공고 비교기준 중 하나).',
    conditions: [
      { kind: 'required', text: '연매출 1억 400만원 미만' },
      { kind: 'required', text: '업력 7년 미만' },
      { kind: 'required', text: '매출 15% 이상 감소 — 전년 대비 연매출, 직전 반기 대비, 직전 분기 대비 등 공고에서 정한 비교기간 중 하나 충족' },
    ],
    criteria: { sales_max_exclusive: 10400, max_biz_age_exclusive: 7, requires_sales_decline_pct: 15, sales_decline_compare_periods: ['연간', '반기', '분기'] },
    reapply_rule: { type: 'announcement', note: '재신청 제한기간 없음. 공고가 떠야 신청 가능' },
    required_docs: ['사업자등록증명', '부가세과세표준증명(매출 감소 증빙)', '납세증명서(국세)', '지방세 납세증명서'],
    exclusive_group: '소진공_직접대출', // 소진공 직접대출 공통 규칙(한 번에 1개)
    notes: '매출 감소 비교기간은 공고에 따라 전년 대비 연매출 / 반기 대비 / 분기 대비 등으로 열려 있음 — 해당 공고의 비교기준을 확인해서 유리한 것으로 증빙.',
    sort_order: 60,
  },

  // ───────────────────────── 보증기관 (간접대출) ─────────────────────────
  {
    key: 'jaedan',
    name: '신용보증재단',
    institution: '지역신용보증재단',
    fund_type: '보증',
    limit_operating: 10000,
    limit_facility: null,
    cap_group: '재단_1억',
    rate_note: '은행 대출금리 적용',
    period_note: '은행별 상이',
    eligibility_summary: '매출 규모와 무관하게, 재단 한도 1억(잔액 합산)을 안 쓰고 있으면 검토 대상. 신보 보증 이용 중이어도 재단 1억을 추가로 받은 사례 있음(매출 17억 대표: 신보 3억 + 재단 1억). 다만 보증기관 간 동시 접수(같은 시기 중복 신청)는 불가.',
    conditions: [
      { kind: 'required', text: '잔여 보증한도 있음 (1억 - 기존 재단 보증 잔액) — 매출 규모 무관하게 미사용이면 검토' },
      { kind: 'required', text: '보증기관 간 동시 접수 아님 (신보·기보와 같은 시기에 중복 신청 불가). 신보 이용 중이어도 순차적으로 재단 추가 받은 사례 있음' },
      { kind: 'required', text: '기존 재단 보증이 있으면 재신청 대기기간 경과' },
    ],
    criteria: {},
    reapply_rule: {
      type: 'months',
      months_by_region: { 수도권: 12, 지방: 6 },
      note: '마지막 보증 수령일 기준. 서울·경기(수도권) 1년 이상, 그 외 지역 6개월 이상. 재단 보증 있으면 반드시 "언제 받으셨나요? 서울/경기인가요?" 먼저 확인.',
    },
    required_docs: ['사업자등록증명', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서', '재무제표(복식부기 대상자)'],
    exclusive_group: '보증기관',
    notes: '소진공 직접대출과 동시진행 순서: ① 소진공 직접대출 접수 → ② 재단 추가 보증 접수 → ③ 보증서 수령 후 대기 → ④ 소진공 심사 완료 후 약정·입금 → ⑤ 보증서 들고 은행 방문하여 보증대출 실행. 신보 대상 규모면 신보가 재단 대출을 대환하며 보증서 재발급하는 경우 있음.',
    sort_order: 100,
  },
  {
    key: 'shinbo',
    name: '신용보증기금 (신보)',
    institution: '신용보증기금',
    fund_type: '보증',
    limit_operating: null,
    limit_facility: null,
    cap_group: null,
    rate_note: '은행 대출금리 적용',
    period_note: '은행별 상이',
    eligibility_summary: '도소매·서비스업 매출 5억 이상(한도 통상 매출÷6 수준), 제조업 매출 3억 이상(한도 통상 매출÷4 수준). 실제 한도는 심사에 따라 위아래로 달라짐(도소매 매출 16억 대표가 3억 받은 사례). 요식업은 원칙적으로 대상 아님(프랜차이즈·가맹은 매출 5억 이상 시 별도 검토).',
    conditions: [
      { kind: 'any', text: '도소매·서비스업: 연매출 5억 이상 → 한도 통상 매출 ÷ 6 수준 (심사에 따라 상이)' },
      { kind: 'any', text: '제조업: 연매출 3억 이상 → 한도 통상 매출 ÷ 4 수준 (심사에 따라 상이)' },
      { kind: 'any', text: '프랜차이즈·가맹 요식업: 연매출 5억 이상 → 한도 통상 매출 ÷ 6 수준 (가맹 여부 등 별도 심사)' },
      { kind: 'required', text: '일반 요식업(비프랜차이즈) 아님 — 원칙적으로 대상 업종 제외' },
      { kind: 'required', text: '기보와 동시 이용 불가 (대환은 예외적 가능하나 대표 보고 후 진행). 재단과는 동시 접수만 불가 — 순차 병행 사례 있음' },
      { kind: 'required', text: '기존 신보 보증이 있으면 1년 경과' },
      { kind: 'bonus', text: '기업부설연구소 보유' },
      { kind: 'bonus', text: '벤처기업 인증' },
    ],
    criteria: {
      limit_formula: { 도소매서비스: { sales_min: 50000, divisor: 6 }, 제조: { sales_min: 30000, divisor: 4 }, 프랜차이즈요식: { sales_min: 50000, divisor: 6 } },
      limit_formula_is_typical: true,
      excluded_industries: ['일반 요식업'],
    },
    reapply_rule: { type: 'months', months: 12, note: '마지막 보증 수령일 기준 1년' },
    required_docs: ['사업자등록증명', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서', '재무제표'],
    exclusive_group: '보증기관',
    notes: '한도 공식(÷6, ÷4)은 통상 수준일 뿐 확정치가 아님 — 안내할 때 "통상적으로"를 붙일 것. 기보 잔액 보유 시 원칙적으로 동시 진행 불가 — 매출·조건 우수 시 대환 검토(상담사 판단). 재단 대출 보유 시 신보가 재단 대출을 대환하며 보증서 재발급하는 경우 있음.',
    sort_order: 110,
  },
  {
    key: 'gibo',
    name: '기술보증기금 (기보)',
    institution: '기술보증기금',
    fund_type: '보증',
    limit_operating: null,
    limit_facility: null,
    cap_group: null,
    rate_note: '은행 대출금리 적용',
    period_note: '은행별 상이',
    eligibility_summary: '기술특허 보유 또는 대표자 경력 10년 이상. 요식업은 원칙적으로 대상 아님. 한도는 매출·기술력을 종합해 보증 심사 시 결정. 재단/신보/기보 중 1개만.',
    conditions: [
      { kind: 'any', text: '기술특허 보유' },
      { kind: 'any', text: '대표자 동업종 경력 10년 이상' },
      { kind: 'required', text: '일반 요식업(비프랜차이즈) 아님 — 원칙적으로 대상 업종 제외' },
      { kind: 'required', text: '신보와 동시 이용 불가 (대환은 예외적 가능하나 대표 보고 후 진행). 재단과는 동시 접수만 불가' },
      { kind: 'required', text: '기존 기보 보증이 있으면 1년 경과' },
      { kind: 'bonus', text: '기업부설연구소 보유 — 있으면 가점, 없어도 신청 가능' },
      { kind: 'bonus', text: '벤처기업 인증 — 있으면 가점, 없어도 신청 가능' },
    ],
    criteria: { requires_patent_or_career_years: 10, excluded_industries: ['일반 요식업'] },
    reapply_rule: { type: 'months', months: 12, note: '마지막 보증 수령일 기준 1년' },
    required_docs: ['사업자등록증명', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서', '재무제표', '특허증 또는 경력 증빙'],
    exclusive_group: '보증기관',
    notes: '기업부설연구소·벤처인증은 가점 요소일 뿐 필수 아님 — 없다고 불가라고 안내하지 말 것. 한도는 특정 금액을 미리 계산해 보여주지 않음.',
    sort_order: 120,
  },

  // ───────────────────────── 중진공 (중소벤처기업진흥공단) ─────────────────────────
  // ※ 아래 중진공 항목은 2026-09-02 웹 조사(중진공 누리집·2026년 융자계획 공고 요약) 기반 초안.
  //    대표가 준 공고문 캡처와 대조해서 확정해야 함. 공통 특성은 공통 규칙 'jungjingong_general' 참고.
  {
    key: 'jungjingong_youth_startup',
    name: '중진공 청년전용창업자금',
    institution: '중소벤처기업진흥공단',
    fund_type: '직접대출',
    limit_operating: 10000,
    limit_facility: 20000,
    cap_group: '중진공_60억',
    rate_note: '2.5% 고정금리 (우대금리 가감 대상 아님)',
    period_note: '직접대출 — 시설 10년 이내(거치: 담보 4년·신용 3년 이내) / 운전 5년 이내(거치 2년 이내)',
    eligibility_summary: '대표자 만 39세 이하 + 업력 3년 미만 중소기업(또는 창업 예정자). 기업당 1억 이내(제조업·중점지원분야는 2억 이내). 미래 성장성·기술력 위주 평가.',
    conditions: [
      { kind: 'required', text: '대표자 만 39세 이하' },
      { kind: 'required', text: '업력 3년 미만 (사업개시일~융자신청서 제출일 기준). 단 청년창업사관학교·글로벌창업사관학교 참여기업, 기보 청년창업기업보증 지원기업, 민간VC 투자유치 기업 중 해당 기관 추천 우수기업은 업력 7년 미만까지' },
      { kind: 'required', text: '융자제외 업종 아님 (숙박·음식점업 등은 제외 대상인 경우가 많음 — 공고의 융자제외 업종표 확인)' },
      { kind: 'bonus', text: '제조업·중점지원분야 영위 → 한도 2억으로 확대' },
      { kind: 'bonus', text: '기술력·사업성 증빙 (특허, 기업부설연구소, 벤처인증 등)' },
    ],
    criteria: { owner_age_max: 39, max_biz_age_exclusive: 3, limit_manufacturing_or_priority: 20000 },
    reapply_rule: { type: 'announcement', note: '연초(1월) 융자계획 공고 후 예산 소진 시까지 상시 접수. 부결 시 다음 회차/연도 공고 확인' },
    required_docs: ['사업자등록증명', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서', '재무제표', '사업계획서', '대표자 신분증(나이 확인)', '기술·사업성 증빙(특허·인증 등, 해당 시)'],
    exclusive_group: null,
    notes: '[웹 조사 초안 — 공고문 대조 필요] 소상공인 규모 넘어도 중소기업이면 가능. 대표 경험상 요식업으로 받는 경우는 본 적 없음(융자제외 업종 영향). 제조·IT 업종이 일반적.',
    sort_order: 200,
    active: true,
  },
  {
    key: 'jungjingong_innovation_startup',
    name: '중진공 혁신창업사업화자금 (창업기반지원)',
    institution: '중소벤처기업진흥공단',
    fund_type: '직접대출',
    limit_operating: 50000,
    limit_facility: 600000,
    cap_group: '중진공_60억',
    rate_note: '정책자금 기준금리(분기별 변동) + 자금종류·신용등급·담보에 따라 가감. 유망기업 인증(소부장 강소기업100·초격차·아기유니콘 등) 0.3%p, 여성·장애인·사회적경제기업 0.3%p, 고용·수출·매출 성과 각 0.1%p 우대(최대 0.4%p)',
    period_note: '시설 10년 이내(거치 4년 이내) / 운전 5년 이내(거치 2년 이내)',
    eligibility_summary: '업력 7년 미만 창업기업(중소기업기본법상 중소기업). 매출 규모가 클수록 유리. 기술·사업성 우수기업 중 민간 금융 이용이 어려운 기업.',
    conditions: [
      { kind: 'required', text: '업력 7년 미만 (7년 이상이면 신성장기반자금으로)' },
      { kind: 'required', text: '중소기업기본법상 중소기업 (소상공인 규모 넘어도 가능)' },
      { kind: 'required', text: '융자제외 업종 아님 (숙박·음식점업 등 제외 — 공고 업종표 확인)' },
      { kind: 'bonus', text: '기업부설연구소·벤처인증·특허 등 기술력 증빙' },
      { kind: 'bonus', text: '매출·고용·수출 성장 실적 (금리 우대 및 평가 가점)' },
    ],
    criteria: { max_biz_age_exclusive: 7 },
    reapply_rule: { type: 'announcement', note: '연초 융자계획 공고 후 예산 소진 시까지 상시 접수. 정책우선도 평가 → 융자신청 → 기업(현장)평가 순' },
    required_docs: ['사업자등록증명', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서', '재무제표', '사업계획서', '기술·인증 증빙(해당 시)'],
    exclusive_group: null,
    notes: '[웹 조사 초안 — 공고문 대조 필요] 한도 수치(운전 5억·시설 60억)는 중진공 일반 융자한도 기준의 추정치. 세부 트랙(일자리창출촉진·개발기술사업화)은 추후 분리.',
    sort_order: 210,
    active: true,
  },
  {
    key: 'jungjingong_growth_base',
    name: '중진공 신성장기반자금',
    institution: '중소벤처기업진흥공단',
    fund_type: '직접대출',
    limit_operating: 50000,
    limit_facility: 600000,
    cap_group: '중진공_60억',
    rate_note: '정책자금 기준금리 + 가감 (우대 최대 0.4%p)',
    period_note: '시설 10년 이내 / 운전 5년 이내',
    eligibility_summary: '업력 7년 이상 성장기 중소기업. 혁신성장지원·제조현장스마트화·Net-Zero 등 세부 트랙. 매출 규모 클수록 유리.',
    conditions: [
      { kind: 'required', text: '업력 7년 이상' },
      { kind: 'required', text: '중소기업기본법상 중소기업' },
      { kind: 'required', text: '융자제외 업종 아님' },
      { kind: 'bonus', text: '스마트공장·디지털전환·탄소중립 투자 계획 (금리 추가 차감 대상)' },
      { kind: 'bonus', text: '기업부설연구소·벤처인증·특허' },
    ],
    criteria: { min_biz_age: 7 },
    reapply_rule: { type: 'announcement', note: '연초 융자계획 공고 후 예산 소진 시까지' },
    required_docs: ['사업자등록증명', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서', '재무제표', '사업계획서'],
    exclusive_group: null,
    notes: '[웹 조사 초안 — 공고문 대조 필요]',
    sort_order: 220,
    active: false,
  },
  {
    key: 'jungjingong_rebound',
    name: '중진공 재도약지원자금',
    institution: '중소벤처기업진흥공단',
    fund_type: '직접대출',
    limit_operating: null,
    limit_facility: null,
    cap_group: '중진공_60억',
    rate_note: '정책자금 기준금리 + 가감',
    period_note: null,
    eligibility_summary: '사업전환·구조개선·재창업 기업 대상. 소진공 재도전특별자금의 중진공 버전 성격.',
    conditions: [
      { kind: 'any', text: '사업전환 계획 승인 기업' },
      { kind: 'any', text: '구조개선(경영정상화) 대상 기업' },
      { kind: 'any', text: '재창업 기업' },
      { kind: 'required', text: '융자제외 업종 아님' },
    ],
    criteria: {},
    reapply_rule: { type: 'announcement', note: '연초 융자계획 공고 후 예산 소진 시까지' },
    required_docs: [],
    exclusive_group: null,
    notes: '[웹 조사 초안 — 한도·세부 조건 미확인, 공고문 대조 필요]',
    sort_order: 230,
    active: false,
  },
]

// 자금 하나에 속하지 않는 공통 규칙. 자격 판정 엔진과 AI 상담 프롬프트가 함께 참조.
export const SEED_COMMON_RULES = [
  {
    key: 'small_business_employee_limit',
    title: '소상공인 기준 (직원 수)',
    content: '대표자 제외 4대보험 가입 직원 기준. 제조·건설·운수·광업: 9명 이하. 그 외(도소매·음식점·서비스 등): 4명 이하. 기준 초과 시 정책자금 신청 불가.',
    params: { limits: { '제조·건설·운수·광업': 9, '그 외': 4 } },
    sort_order: 10,
  },
  {
    key: 'debt_over_sales',
    title: '매출초과차입금 기준',
    content: '업력 7년 미만: 적용 안 함 (대출이 매출보다 많아도 가능). 업력 7년 이상: 연매출 - 사업자대출 잔액 합계가 마이너스면 신청 불가. 사업자대출 = 소진공 + 재단 + 신보 + 기보 + 중진공 + 사업자명의대출 (아파트담보·개인신용대출은 제외).',
    params: { applies_from_biz_age: 7 },
    sort_order: 20,
  },
  {
    key: 'sojinkong_total_cap',
    title: '소진공 직접대출 총한도',
    content: '기본 총한도 1억원 (직접대출 잔액 합산). 혁신형·도약형은 총한도 2억원 별도 적용. 남은 한도 = 총한도 - 현재 소진공 직접대출 잔액. 신용취약소상공인자금은 자금 자체 한도 3천만원(잔액 합산) 별도.',
    params: { cap_groups: { '소진공_기본_1억': 10000, '소진공_확장_2억': 20000, '신용취약_3천': 3000, '재단_1억': 10000, '중진공_60억': 600000 } },
    sort_order: 30,
  },
  {
    key: 'guarantee_exclusive',
    title: '보증기관 중복 규칙',
    content: '신용보증재단 / 신용보증기금(신보) / 기술보증기금(기보)는 같은 시기에 동시 접수 불가. 신보와 기보는 동시 이용 불가(대환은 예외적 가능하나 복잡하므로 대표에게 보고 후 진행). 단, 재단은 매출 규모와 무관하게 1억 한도를 안 쓰고 있으면 검토 대상 — 신보 보증 이용 중인 매출 17억 대표가 재단 1억을 추가로 받은 사례 있음(순차 진행). 요식업·서비스업은 신보/기보 원칙적으로 해당 없음.',
    params: { exclusive_group: '보증기관' },
    sort_order: 40,
  },
  {
    key: 'sojinkong_one_at_a_time',
    title: '소진공 직접대출은 한 번에 1개만',
    content: '소진공 직접대출은 심사 결과가 나올 때까지 한 번에 1개 자금만 접수 가능 (일시적경영애로자금뿐 아니라 모든 직접대출 공통). 대리대출(보증서·확인서 기반으로 은행에서 실행하는 방식)은 별개라 직접대출과 병행 가능.',
    params: { exclusive_group: '소진공_직접대출' },
    sort_order: 45,
  },
  {
    key: 'direct_plus_guarantee',
    title: '직접대출 + 보증 동시진행',
    content: '소진공 직접대출(직접)과 재단·신보·기보(간접/보증)는 서로 다른 방식이라 타이밍만 맞으면 함께 진행 가능. 순서: ① 소진공 직접대출 접수 → ② 보증기관 접수 → ③ 보증서 수령 후 대기 → ④ 소진공 심사 완료 후 약정·입금 → ⑤ 보증서 들고 은행 방문하여 보증대출 실행.',
    params: {},
    sort_order: 50,
  },
  {
    key: 'tax_delinquency',
    title: '체납',
    content: '국세·지방세 체납 중이면 정책자금 신청 불가 (체납 해소 후 신청 가능).',
    params: {},
    sort_order: 60,
  },
  {
    key: 'bonus_points',
    title: '가점 요소 (기관별로 다름)',
    content: '소진공: 노란우산공제, 여성기업확인서, 직접대출 성실상환 이력, 특허보유. 중진공·신보·기보: 기업부설연구소, 벤처인증. 기관별로 다르므로 섞어서 안내하지 않음.',
    params: { 소진공: ['노란우산공제', '여성기업확인서', '직접대출 성실상환 이력', '특허보유'], '중진공·신보·기보': ['기업부설연구소', '벤처인증'] },
    sort_order: 70,
  },
  {
    key: 'jungjingong_general',
    title: '중진공 공통 특성',
    content: '[웹 조사 초안 + 대표 경험] 중소기업기본법상 중소기업 대상이라 소상공인 규모를 넘어도 가능하고, 매출 규모가 클수록 유리. 청년전용창업자금(만 39세 이하)은 미래를 보는 자금이라 기술력 등 외적 요소를 많이 봄. 업종은 제조·IT가 일반적이고 요식업으로 받는 사례는 본 적 없음(숙박·음식점업은 융자제외 업종인 경우가 많음). 기업당 총한도 60억(중진공 대출 잔액 + 신규 합산). 2026년 융자 예산 4조 643억 + 이차보전 3,670억. 신청: 연초(1/5) 공고 후 예산 소진 시까지, 중진공 누리집 "정책자금 내비게이션"에 업력·수출실적·자금용도 입력하면 적합 자금 자동 추천. 절차: 기업정보 입력 → 정책우선도 평가 → 융자신청 → 기업(현장)평가 → 융자결정·대출실행. 6대 자금: 혁신창업사업화(업력 7년 미만), 신성장기반(7년 이상), 신시장진출지원(수출), 재도약지원(사업전환·재창업), 긴급경영안정(재해·일시적경영애로), 청년전용창업. 가점: 기업부설연구소, 벤처인증.',
    params: { total_cap: 600000, youth_age_max: 39 },
    sort_order: 75,
  },
  {
    key: 'consult_principles',
    title: '상담 원칙',
    content: '정보가 없으면 단정짓지 말고 먼저 물어본다. "해당 없음"처럼 소극적으로 끝내지 않고 항상 받을 수 있는 최대 금액을 찾는다. 분석 순서: 직원 수 → 매출초과차입금 → 소진공 잔여한도 → 혁신성장촉진 → 재도전특별 → 재단 동시진행 → 신보/기보 → 최종 진행 순서·예상 총액 정리.',
    params: {},
    sort_order: 80,
  },
]
