// lib/policyFundsSeed.js
// 정책자금 마스터 DB의 초기 데이터.
// 출처: app/api/chat/route.js(AI 상담 시스템 프롬프트), lib/policyFundAnalysis.js, lib/policyFundEstimate.js,
//       app/components/PolicyFundAnalyzer.jsx — 2026-09-02 기준으로 거기 있던 지식을 하나도 빼지 않고 구조화한 것.
// 이 파일은 "DB가 비어있을 때 최초 1회" 채우는 용도. 이후 수정은 /admin/policy-funds 관리자 화면에서 하고,
// 이 파일은 백업/참고용으로만 남겨둠 (관리자 화면에서 고친 내용이 이 파일에 자동 반영되지는 않음).
//
// 금액 단위: 전부 만원.
//
// conditions: [{ text, kind }] — kind는 'required'(전부 충족) 또는 'any'(any끼리 묶어서 그중 1개만 충족하면 됨)
// reapply_rule: { type: 'none' | 'months' | 'announcement', months, months_by_region: {수도권, 지방}, note }
//   - months: 마지막 수령일 기준 재신청 가능까지 개월 수
//   - announcement: 제한기간은 없지만 공고가 떠야 신청 가능 (소진공) → 부결 고객은 공고 알림과 연결
// criteria: 자격 자동판정 엔진이 읽는 수치/플래그 (선택). 없는 키는 판정에서 무시.

export const SEED_FUNDS = [
  // ───────────────────────── 소진공 직접대출 ─────────────────────────
  {
    key: 'sojinkong_hyuksin_general',
    name: '혁신성장촉진자금 일반형',
    institution: '소상공인시장진흥공단',
    fund_type: '직접대출',
    limit_operating: 10000,
    limit_facility: 50000,
    cap_group: '소진공_기본_1억',
    rate_note: '정책자금 기준금리 + 0.4%p',
    period_note: '운전 5년 (거치 2년) / 시설 8년 (거치 3년)',
    eligibility_summary: '아래 스마트기기 중 1개 이상을 도입·운영 중인 소상공인. 소진공 직접대출 총한도 1억(잔액 합산) 안에서 신청.',
    conditions: [
      { kind: 'required', text: '스마트기기 1개 이상 도입·운영 중 (아래 목록 참고)' },
      { kind: 'required', text: '소진공 직접대출 잔여한도 있음 (총한도 1억 - 현재 잔액)' },
    ],
    smart_devices: [
      '3D 풋스캐너 / 3D 프린터',
      'AI CCTV / AI 두피분석 / AI 안면인식',
      'AI·IOT 온도관리시스템',
      '주문·예약·결제 키오스크',
      'QR/NFC 오더 / 테이블 오더',
      'AI·무게형·모듈형 무인판매기',
      '서빙로봇 / 헬퍼로봇 / 조리로봇',
      '디지털광고보드 / 디지털메뉴보드',
      '고객관리·예약·매출분석·재고관리 S/W',
      '온라인예약관리 / 매장멤버십관리시스템',
      '축산 육가공공정시스템',
    ],
    criteria: { requires_smart_device: true },
    reapply_rule: { type: 'announcement', note: '재신청 제한기간 없음. 공고가 떠야 신청 가능 — 부결 시 다음 공고 알림과 연결' },
    required_docs: ['사업자등록증명', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서', '스마트기기 도입 증빙(구매계약서·영수증·사진 등)'],
    exclusive_group: null,
    notes: '2026년 4월부터 스마트기기 목록에서 배달앱·자동화기기 삭제됨.',
    sort_order: 10,
  },
  {
    key: 'sojinkong_hyuksin_innovative',
    name: '혁신성장촉진자금 혁신형',
    institution: '소상공인시장진흥공단',
    fund_type: '직접대출',
    limit_operating: 20000,
    limit_facility: 100000,
    cap_group: '소진공_확장_2억',
    rate_note: '정책자금 기준금리 + 0.4%p',
    period_note: '운전 5년 (거치 2년) / 시설 8년 (거치 3년)',
    eligibility_summary: '일반형 요건(스마트기기)을 충족하면서 아래 성장 요건 중 1개 이상 해당. 총한도 2억 별도 적용.',
    conditions: [
      { kind: 'required', text: '스마트기기 1개 이상 도입·운영 중 (일반형 요건)' },
      { kind: 'any', text: '최근 1년 수출 실적 1천달러 이상 (수출실적증명원 발급 가능)' },
      { kind: 'any', text: '23년→24년, 24년→25년 매출 연속 10% 이상 증가 (단 23년 매출 5천만원 이상)' },
      { kind: 'any', text: '소진공 직접대출 원금분할상환 중 또는 최근 3년 내 완제 (거치기간 중이면 해당 안 됨)' },
      { kind: 'any', text: '스마트공장 도입 / 강한소상공인·로컬크리에이터 선정' },
    ],
    criteria: { requires_smart_device: true, credit_min_recommended: 700 },
    reapply_rule: { type: 'announcement', note: '재신청 제한기간 없음. 공고가 떠야 신청 가능' },
    required_docs: ['사업자등록증명', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서', '재무제표(복식부기 대상자)', '수출실적증명원 또는 매출 증가 증빙 등 해당 요건 증빙'],
    exclusive_group: null,
    notes: '신용점수 공식 제한 없으나 실전 기준 700점 이상 권장.',
    sort_order: 20,
  },
  {
    key: 'sojinkong_jaedo_general',
    name: '재도전특별자금 일반형',
    institution: '소상공인시장진흥공단',
    fund_type: '직접대출',
    limit_operating: 7000,
    limit_facility: null,
    cap_group: '소진공_기본_1억',
    rate_note: '정책자금 기준금리 + 0.4%p',
    period_note: '운전 5년 (거치 2년) / 시설 8년 (거치 3년)',
    eligibility_summary: '현재 사업자 1개 + 업력 7년 미만이면서, 폐업이력 등 재도전 사유가 있는 소상공인.',
    conditions: [
      { kind: 'required', text: '현재 대표자 명의 사업자 1개 (2개 이상이면 불가)' },
      { kind: 'required', text: '업력 7년 미만' },
      { kind: 'any', text: '과거 폐업 이력 있음' },
      { kind: 'any', text: '업종 전환 이력 있음' },
      { kind: 'any', text: '3개월 이상 휴업 이력 있음' },
      { kind: 'any', text: '매출 감소로 사업장 이전 이력 있음' },
    ],
    criteria: { max_biz_age_exclusive: 7, current_biz_count: 1, requires_closure_or_restart_history: true },
    reapply_rule: { type: 'announcement', note: '재신청 제한기간 없음. 공고가 떠야 신청 가능' },
    required_docs: ['사업자등록증명', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서', '폐업사실증명(폐업이력 증빙) 또는 해당 사유 증빙'],
    exclusive_group: null,
    notes: '폐업사실증명 API는 CODEF에서 2026년 9월 중 제공 예정.',
    sort_order: 30,
  },
  {
    key: 'sojinkong_jaedo_leap',
    name: '재도전특별자금 도약형',
    institution: '소상공인시장진흥공단',
    fund_type: '직접대출',
    limit_operating: 20000,
    limit_facility: null,
    cap_group: '소진공_확장_2억',
    rate_note: '정책자금 기준금리 + 0.4%p',
    period_note: '운전 5년 (거치 2년) / 시설 8년 (거치 3년)',
    eligibility_summary: '재창업 업력 2~7년 + 소진공 성실상환 + 성장 요건 중 1개.',
    conditions: [
      { kind: 'required', text: '재창업 업력 2년 이상 7년 미만' },
      { kind: 'required', text: '소진공 직접대출 성실상환 (원금분할상환 중)' },
      { kind: 'any', text: '직원 2명 이상' },
      { kind: 'any', text: '24년→25년 매출 5% 이상 증가' },
      { kind: 'any', text: '최근 6개월 vs 이전 6개월 매출 5% 이상 증가' },
    ],
    criteria: { min_biz_age: 2, max_biz_age_exclusive: 7, requires_sojinkong_good_repayment: true },
    reapply_rule: { type: 'announcement', note: '재신청 제한기간 없음. 공고가 떠야 신청 가능' },
    required_docs: ['사업자등록증명', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서', '재무제표(복식부기 대상자)', '4대보험 가입자명부(직원 요건 시)'],
    exclusive_group: null,
    notes: null,
    sort_order: 40,
  },
  {
    key: 'sojinkong_credit_vulnerable',
    name: '신용취약소상공인자금',
    institution: '소상공인시장진흥공단',
    fund_type: '직접대출',
    limit_operating: 3000,
    limit_facility: null,
    cap_group: '신용취약_3천',
    rate_note: '정책자금 기준금리 + 0.4%p',
    period_note: '5년 (거치 2년)',
    eligibility_summary: 'NICE 신용점수 595~839점 구간 + 국세·지방세 체납 없음 + 연체 없음. 자금 자체 한도 3천만원(잔액 합산).',
    conditions: [
      { kind: 'required', text: 'NICE 신용점수 595점 이상 839점 이하' },
      { kind: 'required', text: '국세·지방세 체납 없음' },
      { kind: 'required', text: '금융권 연체 없음' },
      { kind: 'required', text: '이 자금 잔여한도 있음 (3천만원 - 기존 신용취약자금 잔액)' },
    ],
    criteria: { credit_min: 595, credit_max: 839, no_tax_delinquency: true, no_overdue: true },
    reapply_rule: { type: 'announcement', note: '재신청 제한기간 없음. 공고가 떠야 신청 가능' },
    required_docs: ['사업자등록증명', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서'],
    exclusive_group: null,
    notes: '신용점수 839점 초과면 대상 범위 초과, 595점 미달이면 최저 기준 미달.',
    sort_order: 50,
  },
  {
    key: 'sojinkong_temporary_hardship',
    name: '일시적경영애로자금',
    institution: '소상공인시장진흥공단',
    fund_type: '직접대출',
    limit_operating: 7000,
    limit_facility: null,
    cap_group: '소진공_기본_1억',
    rate_note: '정책자금 기준금리 + 0.4%p',
    period_note: '운전 5년 (거치 2년)',
    eligibility_summary: '연매출 1억 400만원 미만 + 업력 7년 미만 + 매출 15% 이상 감소. 다른 소진공 직접대출과 동시 진행 불가.',
    conditions: [
      { kind: 'required', text: '연매출 1억 400만원 미만' },
      { kind: 'required', text: '업력 7년 미만' },
      { kind: 'required', text: '매출 15% 이상 감소' },
    ],
    criteria: { sales_max_exclusive: 10400, max_biz_age_exclusive: 7, requires_sales_decline_pct: 15 },
    reapply_rule: { type: 'announcement', note: '재신청 제한기간 없음. 공고가 떠야 신청 가능' },
    required_docs: ['사업자등록증명', '부가세과세표준증명(매출 감소 증빙)', '납세증명서(국세)', '지방세 납세증명서'],
    exclusive_group: '소진공_직접대출_동시불가',
    notes: '다른 소진공 직접대출과 동시 진행 불가.',
    sort_order: 60,
  },

  // ───────────────────────── 보증기관 (간접대출) ─────────────────────────
  {
    key: 'jaedan',
    name: '신용보증재단',
    institution: '지역신용보증재단',
    fund_type: '보증',
    limit_operating: 10000,
    limit_facility: null,
    cap_group: '재단_1억',
    rate_note: '은행 대출금리 적용',
    period_note: '은행별 상이',
    eligibility_summary: '매출 5억 미만 소상공인 대부분 해당. 한도 1억(잔액 합산). 재단/신보/기보 중 1개만 선택 가능.',
    conditions: [
      { kind: 'required', text: '소상공인 (매출 5억 미만 대부분 해당)' },
      { kind: 'required', text: '잔여 보증한도 있음 (1억 - 기존 재단 보증 잔액)' },
      { kind: 'required', text: '신보·기보 이용 중이 아님 (보증기관 중 1개만)' },
      { kind: 'required', text: '기존 재단 보증이 있으면 재신청 대기기간 경과' },
    ],
    criteria: {},
    reapply_rule: {
      type: 'months',
      months_by_region: { 수도권: 12, 지방: 6 },
      note: '마지막 보증 수령일 기준. 서울·경기(수도권) 1년 이상, 그 외 지역 6개월 이상. 재단 보증 있으면 반드시 "언제 받으셨나요? 서울/경기인가요?" 먼저 확인.',
    },
    required_docs: ['사업자등록증명', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서', '재무제표(복식부기 대상자)'],
    exclusive_group: '보증기관',
    notes: '소진공 직접대출과 동시진행 순서: ① 소진공 직접대출 접수 → ② 재단 추가 보증 접수 → ③ 보증서 수령 후 대기 → ④ 소진공 심사 완료 후 약정·입금 → ⑤ 보증서 들고 은행 방문하여 보증대출 실행. 신보 대상 규모면 신보가 재단 대출을 대환하며 보증서 재발급하는 경우 있음.',
    sort_order: 100,
  },
  {
    key: 'shinbo',
    name: '신용보증기금 (신보)',
    institution: '신용보증기금',
    fund_type: '보증',
    limit_operating: null,
    limit_facility: null,
    cap_group: null,
    rate_note: '은행 대출금리 적용',
    period_note: '은행별 상이',
    eligibility_summary: '도소매·서비스업 매출 5억 이상(한도=매출÷6), 제조업 매출 3억 이상(한도=매출÷4). 요식업은 원칙적으로 대상 아님(프랜차이즈·가맹은 매출 5억 이상 시 별도 검토). 재단/신보/기보 중 1개만.',
    conditions: [
      { kind: 'any', text: '도소매·서비스업: 연매출 5억 이상 → 한도 = 매출 ÷ 6' },
      { kind: 'any', text: '제조업: 연매출 3억 이상 → 한도 = 매출 ÷ 4' },
      { kind: 'any', text: '프랜차이즈·가맹 요식업: 연매출 5억 이상 → 한도 = 매출 ÷ 6 (가맹 여부 등 별도 심사)' },
      { kind: 'required', text: '일반 요식업(비프랜차이즈) 아님 — 원칙적으로 대상 업종 제외' },
      { kind: 'required', text: '재단·기보 이용 중이 아님 (보증기관 중 1개만; 대환은 예외적 가능하나 대표 보고 후 진행)' },
      { kind: 'required', text: '기존 신보 보증이 있으면 1년 경과' },
    ],
    criteria: {
      limit_formula: { 도소매서비스: { sales_min: 50000, divisor: 6 }, 제조: { sales_min: 30000, divisor: 4 }, 프랜차이즈요식: { sales_min: 50000, divisor: 6 } },
      excluded_industries: ['일반 요식업'],
    },
    reapply_rule: { type: 'months', months: 12, note: '마지막 보증 수령일 기준 1년' },
    required_docs: ['사업자등록증명', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서', '재무제표'],
    exclusive_group: '보증기관',
    notes: '가점: 기업부설연구소, 벤처인증. 기보 잔액 보유 시 원칙적으로 동시 진행 불가 — 매출·조건 우수 시 대환 검토(상담사 판단). 재단 대출 보유 시 신보가 재단 대출을 대환하며 보증서 재발급하는 경우 있음.',
    sort_order: 110,
  },
  {
    key: 'gibo',
    name: '기술보증기금 (기보)',
    institution: '기술보증기금',
    fund_type: '보증',
    limit_operating: null,
    limit_facility: null,
    cap_group: null,
    rate_note: '은행 대출금리 적용',
    period_note: '은행별 상이',
    eligibility_summary: '기술특허 보유 또는 대표자 경력 10년 이상. 요식업은 원칙적으로 대상 아님. 한도는 매출·기술력을 종합해 보증 심사 시 결정. 재단/신보/기보 중 1개만.',
    conditions: [
      { kind: 'any', text: '기술특허 보유' },
      { kind: 'any', text: '대표자 동업종 경력 10년 이상' },
      { kind: 'required', text: '일반 요식업(비프랜차이즈) 아님 — 원칙적으로 대상 업종 제외' },
      { kind: 'required', text: '재단·신보 이용 중이 아님 (보증기관 중 1개만; 대환은 예외적 가능하나 대표 보고 후 진행)' },
      { kind: 'required', text: '기존 기보 보증이 있으면 1년 경과' },
    ],
    criteria: { requires_patent_or_career_years: 10, excluded_industries: ['일반 요식업'] },
    reapply_rule: { type: 'months', months: 12, note: '마지막 보증 수령일 기준 1년' },
    required_docs: ['사업자등록증명', '부가세과세표준증명', '납세증명서(국세)', '지방세 납세증명서', '재무제표', '특허증 또는 경력 증빙'],
    exclusive_group: '보증기관',
    notes: '가점: 기업부설연구소, 벤처인증. 한도는 특정 금액을 미리 계산해 보여주지 않음.',
    sort_order: 120,
  },

  // ───────────────────────── 기타 ─────────────────────────
  {
    key: 'jungjingong',
    name: '중진공 (중소벤처기업진흥공단)',
    institution: '중소벤처기업진흥공단',
    fund_type: '직접대출',
    limit_operating: null,
    limit_facility: null,
    cap_group: null,
    rate_note: null,
    period_note: null,
    eligibility_summary: '정확한 심사 기준 미확정 — 상담 시 별도 검토. 가점: 기업부설연구소, 벤처인증.',
    conditions: [
      { kind: 'required', text: '기준 확인 필요 (상담 시 별도 검토)' },
    ],
    criteria: {},
    reapply_rule: { type: 'none', note: '미확정' },
    required_docs: [],
    exclusive_group: null,
    notes: '자격조건·한도·금리·재신청 규칙을 채워야 함.',
    sort_order: 200,
    active: false,
  },
]

// 자금 하나에 속하지 않는 공통 규칙. 자격 판정 엔진과 AI 상담 프롬프트가 함께 참조.
export const SEED_COMMON_RULES = [
  {
    key: 'small_business_employee_limit',
    title: '소상공인 기준 (직원 수)',
    content: '대표자 제외 4대보험 가입 직원 기준. 제조·건설·운수·광업: 9명 이하. 그 외(도소매·음식점·서비스 등): 4명 이하. 기준 초과 시 정책자금 신청 불가.',
    params: { limits: { '제조·건설·운수·광업': 9, '그 외': 4 } },
    sort_order: 10,
  },
  {
    key: 'debt_over_sales',
    title: '매출초과차입금 기준',
    content: '업력 7년 미만: 적용 안 함 (대출이 매출보다 많아도 가능). 업력 7년 이상: 연매출 - 사업자대출 잔액 합계가 마이너스면 신청 불가. 사업자대출 = 소진공 + 재단 + 신보 + 기보 + 중진공 + 사업자명의대출 (아파트담보·개인신용대출은 제외).',
    params: { applies_from_biz_age: 7 },
    sort_order: 20,
  },
  {
    key: 'sojinkong_total_cap',
    title: '소진공 직접대출 총한도',
    content: '기본 총한도 1억원 (직접대출 잔액 합산). 혁신형·도약형은 총한도 2억원 별도 적용. 남은 한도 = 총한도 - 현재 소진공 직접대출 잔액. 신용취약소상공인자금은 자금 자체 한도 3천만원(잔액 합산) 별도.',
    params: { cap_groups: { '소진공_기본_1억': 10000, '소진공_확장_2억': 20000, '신용취약_3천': 3000, '재단_1억': 10000 } },
    sort_order: 30,
  },
  {
    key: 'guarantee_exclusive',
    title: '보증기관 중복 금지',
    content: '신용보증재단 / 신용보증기금(신보) / 기술보증기금(기보) 중 1개만 선택 가능. 동시 접수 절대 불가. 신보와 기보도 동시 이용 불가. 대환(한 기관이 다른 기관 대출을 갚아주고 추가대출)은 예외적으로 가능하나 복잡하므로 대표에게 보고 후 진행. 요식업·서비스업은 신보/기보 원칙적으로 해당 없음.',
    params: { exclusive_group: '보증기관' },
    sort_order: 40,
  },
  {
    key: 'direct_plus_guarantee',
    title: '직접대출 + 보증 동시진행',
    content: '소진공 직접대출(직접)과 재단·신보·기보(간접/보증)는 서로 다른 방식이라 타이밍만 맞으면 함께 진행 가능. 순서: ① 소진공 직접대출 접수 → ② 보증기관 접수 → ③ 보증서 수령 후 대기 → ④ 소진공 심사 완료 후 약정·입금 → ⑤ 보증서 들고 은행 방문하여 보증대출 실행.',
    params: {},
    sort_order: 50,
  },
  {
    key: 'tax_delinquency',
    title: '체납',
    content: '국세·지방세 체납 중이면 정책자금 신청 불가 (체납 해소 후 신청 가능).',
    params: {},
    sort_order: 60,
  },
  {
    key: 'bonus_points',
    title: '가점 요소 (기관별로 다름)',
    content: '소진공: 노란우산공제, 여성기업확인서, 직접대출 성실상환 이력, 특허보유. 중진공·신보·기보: 기업부설연구소, 벤처인증. 기관별로 다르므로 섞어서 안내하지 않음.',
    params: { 소진공: ['노란우산공제', '여성기업확인서', '직접대출 성실상환 이력', '특허보유'], '중진공·신보·기보': ['기업부설연구소', '벤처인증'] },
    sort_order: 70,
  },
  {
    key: 'consult_principles',
    title: '상담 원칙',
    content: '정보가 없으면 단정짓지 말고 먼저 물어본다. "해당 없음"처럼 소극적으로 끝내지 않고 항상 받을 수 있는 최대 금액을 찾는다. 분석 순서: 직원 수 → 매출초과차입금 → 소진공 잔여한도 → 혁신성장촉진 → 재도전특별 → 재단 동시진행 → 신보/기보 → 최종 진행 순서·예상 총액 정리.',
    params: {},
    sort_order: 80,
  },
]
